package org.AgileKartRest.model;

// Generated May 23, 2015 8:30:37 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.xml.bind.annotation.XmlRootElement;

import org.codehaus.jackson.annotate.JsonIgnoreProperties;

/**
 * AkOptionGroups generated by hbm2java
 */
@Entity
@Table(name = "ak_option_groups"
      , catalog = "agilekart"
      , uniqueConstraints = @UniqueConstraint(columnNames = "option_group_name"))
@JsonIgnoreProperties({ "akProductOptionses","akOptionses"})
@XmlRootElement
public class AkOptionGroups implements java.io.Serializable
{

   private Integer optionGroupId;
   private String optionGroupName;
   private Set<AkProductOptions> akProductOptionses = new HashSet<AkProductOptions>(0);
   private Set<AkOptions> akOptionses = new HashSet<AkOptions>(0);

   public AkOptionGroups()
   {
   }

   public AkOptionGroups(String optionGroupName)
   {
      this.optionGroupName = optionGroupName;
   }

   public AkOptionGroups(String optionGroupName, Set<AkProductOptions> akProductOptionses, Set<AkOptions> akOptionses)
   {
      this.optionGroupName = optionGroupName;
      this.akProductOptionses = akProductOptionses;
      this.akOptionses = akOptionses;
   }

   @Id
   @GeneratedValue(strategy = IDENTITY)
   @Column(name = "option_group_id", unique = true, nullable = false)
   public Integer getOptionGroupId()
   {
      return this.optionGroupId;
   }

   public void setOptionGroupId(Integer optionGroupId)
   {
      this.optionGroupId = optionGroupId;
   }

   @Column(name = "option_group_name", unique = true, nullable = false, length = 50)
   public String getOptionGroupName()
   {
      return this.optionGroupName;
   }

   public void setOptionGroupName(String optionGroupName)
   {
      this.optionGroupName = optionGroupName;
   }

   @OneToMany(fetch = FetchType.EAGER, mappedBy = "akOptionGroups")
   public Set<AkProductOptions> getAkProductOptionses()
   {
      return this.akProductOptionses;
   }

   public void setAkProductOptionses(Set<AkProductOptions> akProductOptionses)
   {
      this.akProductOptionses = akProductOptionses;
   }

   @OneToMany(fetch = FetchType.EAGER, mappedBy = "akOptionGroups")
   public Set<AkOptions> getAkOptionses()
   {
      return this.akOptionses;
   }

   public void setAkOptionses(Set<AkOptions> akOptionses)
   {
      this.akOptionses = akOptionses;
   }

}
