package org.AgileKartRest.model;

// Generated May 23, 2015 8:30:37 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;

import org.codehaus.jackson.annotate.JsonIgnoreProperties;

/**
 * AkOrders generated by hbm2java
 */
@Entity
@Table(name = "ak_orders"
      , catalog = "agilekart")
@JsonIgnoreProperties({ "akOrderDetailses"})
@XmlRootElement
public class AkOrders implements java.io.Serializable
{

   private Integer orderId;
   private AkUsers akUsers;
   private float orderAmount;
   private String orderShipName;
   private String orderShipAddress;
   private String orderShipAddress2;
   private String orderCity;
   private String orderState;
   private String orderZip;
   private String orderCountry;
   private String orderPhone;
   private String orderFax;
   private float orderShipping;
   private float orderTax;
   private String orderEmail;
   private Date orderDate;
   private boolean orderShipped;
   private String orderTrackingNo;
   private Set<AkOrderDetails> akOrderDetailses = new HashSet<AkOrderDetails>(0);

   public AkOrders()
   {
   }

   public AkOrders(AkUsers akUsers, float orderAmount, String orderShipName, String orderShipAddress, String orderShipAddress2, String orderCity, String orderState, String orderZip, String orderCountry, String orderPhone, String orderFax, float orderShipping, float orderTax, String orderEmail, Date orderDate, boolean orderShipped)
   {
      this.akUsers = akUsers;
      this.orderAmount = orderAmount;
      this.orderShipName = orderShipName;
      this.orderShipAddress = orderShipAddress;
      this.orderShipAddress2 = orderShipAddress2;
      this.orderCity = orderCity;
      this.orderState = orderState;
      this.orderZip = orderZip;
      this.orderCountry = orderCountry;
      this.orderPhone = orderPhone;
      this.orderFax = orderFax;
      this.orderShipping = orderShipping;
      this.orderTax = orderTax;
      this.orderEmail = orderEmail;
      this.orderDate = orderDate;
      this.orderShipped = orderShipped;
   }

   public AkOrders(AkUsers akUsers, float orderAmount, String orderShipName, String orderShipAddress, String orderShipAddress2, String orderCity, String orderState, String orderZip, String orderCountry, String orderPhone, String orderFax, float orderShipping, float orderTax, String orderEmail, Date orderDate, boolean orderShipped, String orderTrackingNo, Set<AkOrderDetails> akOrderDetailses)
   {
      this.akUsers = akUsers;
      this.orderAmount = orderAmount;
      this.orderShipName = orderShipName;
      this.orderShipAddress = orderShipAddress;
      this.orderShipAddress2 = orderShipAddress2;
      this.orderCity = orderCity;
      this.orderState = orderState;
      this.orderZip = orderZip;
      this.orderCountry = orderCountry;
      this.orderPhone = orderPhone;
      this.orderFax = orderFax;
      this.orderShipping = orderShipping;
      this.orderTax = orderTax;
      this.orderEmail = orderEmail;
      this.orderDate = orderDate;
      this.orderShipped = orderShipped;
      this.orderTrackingNo = orderTrackingNo;
      this.akOrderDetailses = akOrderDetailses;
   }

   @Id
   @GeneratedValue(strategy = IDENTITY)
   @Column(name = "order_id", unique = true, nullable = false)
   public Integer getOrderId()
   {
      return this.orderId;
   }

   public void setOrderId(Integer orderId)
   {
      this.orderId = orderId;
   }

   @ManyToOne(fetch = FetchType.EAGER)
   @JoinColumn(name = "user_id", nullable = false)
   public AkUsers getAkUsers()
   {
      return this.akUsers;
   }

   public void setAkUsers(AkUsers akUsers)
   {
      this.akUsers = akUsers;
   }

   @Column(name = "order_amount", nullable = false, precision = 12, scale = 0)
   public float getOrderAmount()
   {
      return this.orderAmount;
   }

   public void setOrderAmount(float orderAmount)
   {
      this.orderAmount = orderAmount;
   }

   @Column(name = "order_ship_name", nullable = false, length = 100)
   public String getOrderShipName()
   {
      return this.orderShipName;
   }

   public void setOrderShipName(String orderShipName)
   {
      this.orderShipName = orderShipName;
   }

   @Column(name = "order_ship_address", nullable = false, length = 100)
   public String getOrderShipAddress()
   {
      return this.orderShipAddress;
   }

   public void setOrderShipAddress(String orderShipAddress)
   {
      this.orderShipAddress = orderShipAddress;
   }

   @Column(name = "order_ship_address2", nullable = false, length = 100)
   public String getOrderShipAddress2()
   {
      return this.orderShipAddress2;
   }

   public void setOrderShipAddress2(String orderShipAddress2)
   {
      this.orderShipAddress2 = orderShipAddress2;
   }

   @Column(name = "order_city", nullable = false, length = 50)
   public String getOrderCity()
   {
      return this.orderCity;
   }

   public void setOrderCity(String orderCity)
   {
      this.orderCity = orderCity;
   }

   @Column(name = "order_state", nullable = false, length = 50)
   public String getOrderState()
   {
      return this.orderState;
   }

   public void setOrderState(String orderState)
   {
      this.orderState = orderState;
   }

   @Column(name = "order_zip", nullable = false, length = 20)
   public String getOrderZip()
   {
      return this.orderZip;
   }

   public void setOrderZip(String orderZip)
   {
      this.orderZip = orderZip;
   }

   @Column(name = "order_country", nullable = false, length = 50)
   public String getOrderCountry()
   {
      return this.orderCountry;
   }

   public void setOrderCountry(String orderCountry)
   {
      this.orderCountry = orderCountry;
   }

   @Column(name = "order_phone", nullable = false, length = 20)
   public String getOrderPhone()
   {
      return this.orderPhone;
   }

   public void setOrderPhone(String orderPhone)
   {
      this.orderPhone = orderPhone;
   }

   @Column(name = "order_fax", nullable = false, length = 20)
   public String getOrderFax()
   {
      return this.orderFax;
   }

   public void setOrderFax(String orderFax)
   {
      this.orderFax = orderFax;
   }

   @Column(name = "order_shipping", nullable = false, precision = 12, scale = 0)
   public float getOrderShipping()
   {
      return this.orderShipping;
   }

   public void setOrderShipping(float orderShipping)
   {
      this.orderShipping = orderShipping;
   }

   @Column(name = "order_tax", nullable = false, precision = 12, scale = 0)
   public float getOrderTax()
   {
      return this.orderTax;
   }

   public void setOrderTax(float orderTax)
   {
      this.orderTax = orderTax;
   }

   @Column(name = "order_email", nullable = false, length = 100)
   public String getOrderEmail()
   {
      return this.orderEmail;
   }

   public void setOrderEmail(String orderEmail)
   {
      this.orderEmail = orderEmail;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "order_date", nullable = false, length = 19)
   public Date getOrderDate()
   {
      return this.orderDate;
   }

   public void setOrderDate(Date orderDate)
   {
      this.orderDate = orderDate;
   }

   @Column(name = "order_shipped",  columnDefinition = "BIT" ,nullable = false)
   public boolean isOrderShipped()
   {
      return this.orderShipped;
   }

   public void setOrderShipped(boolean orderShipped)
   {
      this.orderShipped = orderShipped;
   }

   @Column(name = "order_tracking_no", length = 80)
   public String getOrderTrackingNo()
   {
      return this.orderTrackingNo;
   }

   public void setOrderTrackingNo(String orderTrackingNo)
   {
      this.orderTrackingNo = orderTrackingNo;
   }

   @OneToMany(fetch = FetchType.EAGER, mappedBy = "akOrders")
   public Set<AkOrderDetails> getAkOrderDetailses()
   {
      return this.akOrderDetailses;
   }

   public void setAkOrderDetailses(Set<AkOrderDetails> akOrderDetailses)
   {
      this.akOrderDetailses = akOrderDetailses;
   }

}
