package org.AgileKartRest.model;

// Generated 12 Aug, 2015 11:27:47 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * CategoryOptions generated by hbm2java
 */
@Entity
@Table(name = "category_options"
      , catalog = "agilekartv2")
@XmlRootElement
public class CategoryOptions implements java.io.Serializable
{
	private static final long serialVersionUID = 1087058539743896647L;
private String categoryOptionsId;
   private Category category;
   private OptionGroups optionGroups;
   private String lastUpdateUserId;
   private Date lastUpdateTs;

   public CategoryOptions()
   {
   }

   public CategoryOptions(String categoryOptionsId)
   {
      this.categoryOptionsId = categoryOptionsId;
   }

   public CategoryOptions(String categoryOptionsId, Category category, OptionGroups optionGroups, String lastUpdateUserId, Date lastUpdateTs)
   {
      this.categoryOptionsId = categoryOptionsId;
      this.category = category;
      this.optionGroups = optionGroups;
      this.lastUpdateUserId = lastUpdateUserId;
      this.lastUpdateTs = lastUpdateTs;
   }

   @Id
   @Column(name = "category_options_id", unique = true, nullable = false, length = 45)
   public String getCategoryOptionsId()
   {
      return this.categoryOptionsId;
   }

   public void setCategoryOptionsId(String categoryOptionsId)
   {
      this.categoryOptionsId = categoryOptionsId;
   }

   @ManyToOne(fetch = FetchType.EAGER)
   @JoinColumn(name = "category_id")
   public Category getCategory()
   {
      return this.category;
   }

   public void setCategory(Category category)
   {
      this.category = category;
   }

   @ManyToOne(fetch = FetchType.EAGER)
   @JoinColumn(name = "option_group_id")
   public OptionGroups getOptionGroups()
   {
      return this.optionGroups;
   }

   public void setOptionGroups(OptionGroups optionGroups)
   {
      this.optionGroups = optionGroups;
   }

   @Column(name = "last_update_user_id", length = 45)
   public String getLastUpdateUserId()
   {
      return this.lastUpdateUserId;
   }

   public void setLastUpdateUserId(String lastUpdateUserId)
   {
      this.lastUpdateUserId = lastUpdateUserId;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "last_update_ts", length = 19)
   public Date getLastUpdateTs()
   {
      return this.lastUpdateTs;
   }

   public void setLastUpdateTs(Date lastUpdateTs)
   {
      this.lastUpdateTs = lastUpdateTs;
   }

}
