package org.AgileKartRest.model;

// Generated 12 Aug, 2015 11:27:47 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;

import org.codehaus.jackson.annotate.JsonIgnoreProperties;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "category"
      , catalog = "agilekartv2")
@JsonIgnoreProperties({ "productCategories","merchantCategories","categoryOptionses"})
@XmlRootElement
public class Category implements java.io.Serializable
{

	private static final long serialVersionUID = 6783638346080630704L;
private String categoryId;
   private String categoryName;
   private String lastUpdateUserId;
   private Date lastUpdateTs;
   private Set<ProductCategory> productCategories = new HashSet<ProductCategory>(0);
   private Set<MerchantCategory> merchantCategories = new HashSet<MerchantCategory>(0);
   private Set<CategoryOptions> categoryOptionses = new HashSet<CategoryOptions>(0);

   public Category()
   {
   }

   public Category(String categoryId)
   {
      this.categoryId = categoryId;
   }

   public Category(String categoryId, String categoryName, String lastUpdateUserId, Date lastUpdateTs, Set<ProductCategory> productCategories, Set<MerchantCategory> merchantCategories, Set<CategoryOptions> categoryOptionses)
   {
      this.categoryId = categoryId;
      this.categoryName = categoryName;
      this.lastUpdateUserId = lastUpdateUserId;
      this.lastUpdateTs = lastUpdateTs;
      this.productCategories = productCategories;
      this.merchantCategories = merchantCategories;
      this.categoryOptionses = categoryOptionses;
   }

   @Id
   @Column(name = "category_id", unique = true, nullable = false, length = 45)
   public String getCategoryId()
   {
      return this.categoryId;
   }

   public void setCategoryId(String categoryId)
   {
      this.categoryId = categoryId;
   }

   @Column(name = "category_name", length = 45)
   public String getCategoryName()
   {
      return this.categoryName;
   }

   public void setCategoryName(String categoryName)
   {
      this.categoryName = categoryName;
   }

   @Column(name = "last_update_user_id", length = 45)
   public String getLastUpdateUserId()
   {
      return this.lastUpdateUserId;
   }

   public void setLastUpdateUserId(String lastUpdateUserId)
   {
      this.lastUpdateUserId = lastUpdateUserId;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "last_update_ts", length = 19)
   public Date getLastUpdateTs()
   {
      return this.lastUpdateTs;
   }

   public void setLastUpdateTs(Date lastUpdateTs)
   {
      this.lastUpdateTs = lastUpdateTs;
   }

   @OneToMany(fetch = FetchType.EAGER, mappedBy = "category")
   public Set<ProductCategory> getProductCategories()
   {
      return this.productCategories;
   }

   public void setProductCategories(Set<ProductCategory> productCategories)
   {
      this.productCategories = productCategories;
   }

   @OneToMany(fetch = FetchType.EAGER, mappedBy = "category")
   public Set<MerchantCategory> getMerchantCategories()
   {
      return this.merchantCategories;
   }

   public void setMerchantCategories(Set<MerchantCategory> merchantCategories)
   {
      this.merchantCategories = merchantCategories;
   }

   @OneToMany(fetch = FetchType.EAGER, mappedBy = "category")
   public Set<CategoryOptions> getCategoryOptionses()
   {
      return this.categoryOptionses;
   }

   public void setCategoryOptionses(Set<CategoryOptions> categoryOptionses)
   {
      this.categoryOptionses = categoryOptionses;
   }

}
