package org.AgileKartRest.model;

// Generated 12 Aug, 2015 11:27:47 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;

import org.codehaus.jackson.annotate.JsonIgnoreProperties;

/**
 * Features generated by hbm2java
 */
@Entity
@Table(name = "features"
      , catalog = "agilekartv2")
@JsonIgnoreProperties({ "merchantFeatureses","featureOptionses"})
@XmlRootElement
public class Features implements java.io.Serializable
{

   /**
	 * 
	 */
	private static final long serialVersionUID = -7372215302510128982L;
private String featureId;
   private String featureName;
   private String lastUpdateUserId;
   private Date lastUpdateTs;
   private Set<FeatureOptions> featureOptionses = new HashSet<FeatureOptions>(0);
   private Set<MerchantFeatures> merchantFeatureses = new HashSet<MerchantFeatures>(0);

   public Features()
   {
   }

   public Features(String featureId)
   {
      this.featureId = featureId;
   }

   public Features(String featureId, String featureName, String lastUpdateUserId, Date lastUpdateTs, Set<FeatureOptions> featureOptionses, Set<MerchantFeatures> merchantFeatureses)
   {
      this.featureId = featureId;
      this.featureName = featureName;
      this.lastUpdateUserId = lastUpdateUserId;
      this.lastUpdateTs = lastUpdateTs;
      this.featureOptionses = featureOptionses;
      this.merchantFeatureses = merchantFeatureses;
   }

   @Id
   @Column(name = "feature_id", unique = true, nullable = false, length = 45)
   public String getFeatureId()
   {
      return this.featureId;
   }

   public void setFeatureId(String featureId)
   {
      this.featureId = featureId;
   }

   @Column(name = "feature_name", length = 45)
   public String getFeatureName()
   {
      return this.featureName;
   }

   public void setFeatureName(String featureName)
   {
      this.featureName = featureName;
   }

   @Column(name = "last_update_user_id", length = 45)
   public String getLastUpdateUserId()
   {
      return this.lastUpdateUserId;
   }

   public void setLastUpdateUserId(String lastUpdateUserId)
   {
      this.lastUpdateUserId = lastUpdateUserId;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "last_update_ts", length = 19)
   public Date getLastUpdateTs()
   {
      return this.lastUpdateTs;
   }

   public void setLastUpdateTs(Date lastUpdateTs)
   {
      this.lastUpdateTs = lastUpdateTs;
   }

   @OneToMany(fetch = FetchType.EAGER, mappedBy = "features")
   public Set<FeatureOptions> getFeatureOptionses()
   {
      return this.featureOptionses;
   }

   public void setFeatureOptionses(Set<FeatureOptions> featureOptionses)
   {
      this.featureOptionses = featureOptionses;
   }

   @OneToMany(fetch = FetchType.EAGER, mappedBy = "features")
   public Set<MerchantFeatures> getMerchantFeatureses()
   {
      return this.merchantFeatureses;
   }

   public void setMerchantFeatureses(Set<MerchantFeatures> merchantFeatureses)
   {
      this.merchantFeatureses = merchantFeatureses;
   }

}
