package org.AgileKartRest.model;

// Generated 12 Aug, 2015 11:27:47 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;

import org.codehaus.jackson.annotate.JsonIgnoreProperties;

/**
 * FeatureOptions generated by hbm2java
 */
@Entity
@Table(name = "feature_options"
      , catalog = "agilekartv2")
@JsonIgnoreProperties({ "merchantFeatureses"})
@XmlRootElement
public class FeatureOptions implements java.io.Serializable
{
	private static final long serialVersionUID = -467725079103092167L;
private String featureOptionsId;
   private Features features;
   private String featureOptionName;
   private String lastUpdateUserId;
   private Date lastUpdateTs;
   private Set<MerchantFeatures> merchantFeatureses = new HashSet<MerchantFeatures>(0);

   public FeatureOptions()
   {
   }

   public FeatureOptions(String featureOptionsId, Features features)
   {
      this.featureOptionsId = featureOptionsId;
      this.features = features;
   }

   public FeatureOptions(String featureOptionsId, Features features, String featureOptionName, String lastUpdateUserId, Date lastUpdateTs, Set<MerchantFeatures> merchantFeatureses)
   {
      this.featureOptionsId = featureOptionsId;
      this.features = features;
      this.featureOptionName = featureOptionName;
      this.lastUpdateUserId = lastUpdateUserId;
      this.lastUpdateTs = lastUpdateTs;
      this.merchantFeatureses = merchantFeatureses;
   }

   @Id
   @Column(name = "feature_options_id", unique = true, nullable = false, length = 45)
   public String getFeatureOptionsId()
   {
      return this.featureOptionsId;
   }

   public void setFeatureOptionsId(String featureOptionsId)
   {
      this.featureOptionsId = featureOptionsId;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "feature_id", nullable = false)
   public Features getFeatures()
   {
      return this.features;
   }

   public void setFeatures(Features features)
   {
      this.features = features;
   }

   @Column(name = "feature_option_name", length = 45)
   public String getFeatureOptionName()
   {
      return this.featureOptionName;
   }

   public void setFeatureOptionName(String featureOptionName)
   {
      this.featureOptionName = featureOptionName;
   }

   @Column(name = "last_update_user_id", length = 45)
   public String getLastUpdateUserId()
   {
      return this.lastUpdateUserId;
   }

   public void setLastUpdateUserId(String lastUpdateUserId)
   {
      this.lastUpdateUserId = lastUpdateUserId;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "last_update_ts", length = 19)
   public Date getLastUpdateTs()
   {
      return this.lastUpdateTs;
   }

   public void setLastUpdateTs(Date lastUpdateTs)
   {
      this.lastUpdateTs = lastUpdateTs;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "featureOptions")
   public Set<MerchantFeatures> getMerchantFeatureses()
   {
      return this.merchantFeatureses;
   }

   public void setMerchantFeatureses(Set<MerchantFeatures> merchantFeatureses)
   {
      this.merchantFeatureses = merchantFeatureses;
   }

}
