package org.AgileKartRest.model;

// Generated 12 Aug, 2015 11:27:47 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * LoyaltyEventDetails generated by hbm2java
 */
@Entity
@Table(name = "loyalty_event_details"
      , catalog = "agilekartv2")
@XmlRootElement
public class LoyaltyEventDetails implements java.io.Serializable
{
	private static final long serialVersionUID = 3917276189209252379L;
private String loyaltyEventDetailsId;
   private Event event;
   private LoyaltyProgramTier loyaltyProgramTier;
   private Integer pointsEarned;
   private String lastUpdateUserId;
   private Date lastUpdateTs;

   public LoyaltyEventDetails()
   {
   }

   public LoyaltyEventDetails(String loyaltyEventDetailsId, Event event, LoyaltyProgramTier loyaltyProgramTier)
   {
      this.loyaltyEventDetailsId = loyaltyEventDetailsId;
      this.event = event;
      this.loyaltyProgramTier = loyaltyProgramTier;
   }

   public LoyaltyEventDetails(String loyaltyEventDetailsId, Event event, LoyaltyProgramTier loyaltyProgramTier, Integer pointsEarned, String lastUpdateUserId, Date lastUpdateTs)
   {
      this.loyaltyEventDetailsId = loyaltyEventDetailsId;
      this.event = event;
      this.loyaltyProgramTier = loyaltyProgramTier;
      this.pointsEarned = pointsEarned;
      this.lastUpdateUserId = lastUpdateUserId;
      this.lastUpdateTs = lastUpdateTs;
   }

   @Id
   @Column(name = "loyalty_event_details_id", unique = true, nullable = false, length = 45)
   public String getLoyaltyEventDetailsId()
   {
      return this.loyaltyEventDetailsId;
   }

   public void setLoyaltyEventDetailsId(String loyaltyEventDetailsId)
   {
      this.loyaltyEventDetailsId = loyaltyEventDetailsId;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "event_id", nullable = false)
   public Event getEvent()
   {
      return this.event;
   }

   public void setEvent(Event event)
   {
      this.event = event;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "tier_id", nullable = false)
   public LoyaltyProgramTier getLoyaltyProgramTier()
   {
      return this.loyaltyProgramTier;
   }

   public void setLoyaltyProgramTier(LoyaltyProgramTier loyaltyProgramTier)
   {
      this.loyaltyProgramTier = loyaltyProgramTier;
   }

   @Column(name = "points_earned")
   public Integer getPointsEarned()
   {
      return this.pointsEarned;
   }

   public void setPointsEarned(Integer pointsEarned)
   {
      this.pointsEarned = pointsEarned;
   }

   @Column(name = "last_update_user_id", length = 45)
   public String getLastUpdateUserId()
   {
      return this.lastUpdateUserId;
   }

   public void setLastUpdateUserId(String lastUpdateUserId)
   {
      this.lastUpdateUserId = lastUpdateUserId;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "last_update_ts", length = 19)
   public Date getLastUpdateTs()
   {
      return this.lastUpdateTs;
   }

   public void setLastUpdateTs(Date lastUpdateTs)
   {
      this.lastUpdateTs = lastUpdateTs;
   }

}
