package org.AgileKartRest.model;

// Generated 12 Aug, 2015 11:27:47 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * MerchantReview generated by hbm2java
 */
@Entity
@Table(name = "merchant_review"
      , catalog = "agilekartv2")
@XmlRootElement
public class MerchantReview implements java.io.Serializable
{
	private static final long serialVersionUID = -6194467093918199348L;
private String merchantReviewId;
   private Merchant merchant;
   private Users users;
   private String merchantReview;
   private Integer merchantRating;
   private String lastUpdateUserId;
   private Date lastUpdateTs;

   public MerchantReview()
   {
   }

   public MerchantReview(String merchantReviewId, Merchant merchant, Users users, String merchantReview)
   {
      this.merchantReviewId = merchantReviewId;
      this.merchant = merchant;
      this.users = users;
      this.merchantReview = merchantReview;
   }

   public MerchantReview(String merchantReviewId, Merchant merchant, Users users, String merchantReview, Integer merchantRating, String lastUpdateUserId, Date lastUpdateTs)
   {
      this.merchantReviewId = merchantReviewId;
      this.merchant = merchant;
      this.users = users;
      this.merchantReview = merchantReview;
      this.merchantRating = merchantRating;
      this.lastUpdateUserId = lastUpdateUserId;
      this.lastUpdateTs = lastUpdateTs;
   }

   @Id
   @Column(name = "merchant_review_id", unique = true, nullable = false, length = 45)
   public String getMerchantReviewId()
   {
      return this.merchantReviewId;
   }

   public void setMerchantReviewId(String merchantReviewId)
   {
      this.merchantReviewId = merchantReviewId;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "merchant_id", nullable = false)
   public Merchant getMerchant()
   {
      return this.merchant;
   }

   public void setMerchant(Merchant merchant)
   {
      this.merchant = merchant;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "user_id", nullable = false)
   public Users getUsers()
   {
      return this.users;
   }

   public void setUsers(Users users)
   {
      this.users = users;
   }

   @Column(name = "merchant_review", nullable = false, length = 150)
   public String getMerchantReview()
   {
      return this.merchantReview;
   }

   public void setMerchantReview(String merchantReview)
   {
      this.merchantReview = merchantReview;
   }

   @Column(name = "merchant_rating")
   public Integer getMerchantRating()
   {
      return this.merchantRating;
   }

   public void setMerchantRating(Integer merchantRating)
   {
      this.merchantRating = merchantRating;
   }

   @Column(name = "last_update_user_id", length = 45)
   public String getLastUpdateUserId()
   {
      return this.lastUpdateUserId;
   }

   public void setLastUpdateUserId(String lastUpdateUserId)
   {
      this.lastUpdateUserId = lastUpdateUserId;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "last_update_ts", length = 19)
   public Date getLastUpdateTs()
   {
      return this.lastUpdateTs;
   }

   public void setLastUpdateTs(Date lastUpdateTs)
   {
      this.lastUpdateTs = lastUpdateTs;
   }

}
