package org.AgileKartRest.model;

// Generated 12 Aug, 2015 11:27:47 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * MerchantAddress generated by hbm2java
 */
@Entity
@Table(name = "merchant_address"
      , catalog = "agilekartv2")
@XmlRootElement
public class MerchantAddress implements java.io.Serializable
{
	private static final long serialVersionUID = -1367426595269285662L;
private String merchantAddressId;
   private Merchant merchant;
   private String merchantAddress;
   private String merchantAddress2;
   private String merchantCity;
   private String merchantCountry;
   private String merchantFax;
   private String merchantFirstName;
   private String merchantLastName;
   private String merchantPhone;
   private String merchantState;
   private String addressTypeName;
   private String merchantZip;
   private String lastUpdateUserId;
   private Date lastUpdateTs;

   public MerchantAddress()
   {
   }

   public MerchantAddress(String merchantAddressId, Merchant merchant)
   {
      this.merchantAddressId = merchantAddressId;
      this.merchant = merchant;
   }

   public MerchantAddress(String merchantAddressId, Merchant merchant, String merchantAddress, String merchantAddress2, String merchantCity, String merchantCountry, String merchantFax, String merchantFirstName, String merchantLastName, String merchantPhone, String merchantState, String addressTypeName, String merchantZip, String lastUpdateUserId, Date lastUpdateTs)
   {
      this.merchantAddressId = merchantAddressId;
      this.merchant = merchant;
      this.merchantAddress = merchantAddress;
      this.merchantAddress2 = merchantAddress2;
      this.merchantCity = merchantCity;
      this.merchantCountry = merchantCountry;
      this.merchantFax = merchantFax;
      this.merchantFirstName = merchantFirstName;
      this.merchantLastName = merchantLastName;
      this.merchantPhone = merchantPhone;
      this.merchantState = merchantState;
      this.addressTypeName = addressTypeName;
      this.merchantZip = merchantZip;
      this.lastUpdateUserId = lastUpdateUserId;
      this.lastUpdateTs = lastUpdateTs;
   }

   @Id
   @Column(name = "merchant_address_id", unique = true, nullable = false, length = 45)
   public String getMerchantAddressId()
   {
      return this.merchantAddressId;
   }

   public void setMerchantAddressId(String merchantAddressId)
   {
      this.merchantAddressId = merchantAddressId;
   }

   @ManyToOne(fetch = FetchType.EAGER)
   @JoinColumn(name = "merchant_id", nullable = false)
   public Merchant getMerchant()
   {
      return this.merchant;
   }

   public void setMerchant(Merchant merchant)
   {
      this.merchant = merchant;
   }

   @Column(name = "merchant_address", length = 100)
   public String getMerchantAddress()
   {
      return this.merchantAddress;
   }

   public void setMerchantAddress(String merchantAddress)
   {
      this.merchantAddress = merchantAddress;
   }

   @Column(name = "merchant_address2", length = 50)
   public String getMerchantAddress2()
   {
      return this.merchantAddress2;
   }

   public void setMerchantAddress2(String merchantAddress2)
   {
      this.merchantAddress2 = merchantAddress2;
   }

   @Column(name = "merchant_city", length = 90)
   public String getMerchantCity()
   {
      return this.merchantCity;
   }

   public void setMerchantCity(String merchantCity)
   {
      this.merchantCity = merchantCity;
   }

   @Column(name = "merchant_country", length = 20)
   public String getMerchantCountry()
   {
      return this.merchantCountry;
   }

   public void setMerchantCountry(String merchantCountry)
   {
      this.merchantCountry = merchantCountry;
   }

   @Column(name = "merchant_fax", length = 20)
   public String getMerchantFax()
   {
      return this.merchantFax;
   }

   public void setMerchantFax(String merchantFax)
   {
      this.merchantFax = merchantFax;
   }

   @Column(name = "merchant_first_name", length = 50)
   public String getMerchantFirstName()
   {
      return this.merchantFirstName;
   }

   public void setMerchantFirstName(String merchantFirstName)
   {
      this.merchantFirstName = merchantFirstName;
   }

   @Column(name = "merchant_last_name", length = 50)
   public String getMerchantLastName()
   {
      return this.merchantLastName;
   }

   public void setMerchantLastName(String merchantLastName)
   {
      this.merchantLastName = merchantLastName;
   }

   @Column(name = "merchant_phone", length = 20)
   public String getMerchantPhone()
   {
      return this.merchantPhone;
   }

   public void setMerchantPhone(String merchantPhone)
   {
      this.merchantPhone = merchantPhone;
   }

   @Column(name = "merchant_state", length = 20)
   public String getMerchantState()
   {
      return this.merchantState;
   }

   public void setMerchantState(String merchantState)
   {
      this.merchantState = merchantState;
   }

   @Column(name = "address_type_name", length = 50)
   public String getAddressTypeName()
   {
      return this.addressTypeName;
   }

   public void setAddressTypeName(String addressTypeName)
   {
      this.addressTypeName = addressTypeName;
   }

   @Column(name = "merchant_zip", length = 12)
   public String getMerchantZip()
   {
      return this.merchantZip;
   }

   public void setMerchantZip(String merchantZip)
   {
      this.merchantZip = merchantZip;
   }

   @Column(name = "last_update_user_id", length = 45)
   public String getLastUpdateUserId()
   {
      return this.lastUpdateUserId;
   }

   public void setLastUpdateUserId(String lastUpdateUserId)
   {
      this.lastUpdateUserId = lastUpdateUserId;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "last_update_ts", length = 19)
   public Date getLastUpdateTs()
   {
      return this.lastUpdateTs;
   }

   public void setLastUpdateTs(Date lastUpdateTs)
   {
      this.lastUpdateTs = lastUpdateTs;
   }

}
