package org.AgileKartRest.model;

// Generated 12 Aug, 2015 11:27:47 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * MerchantFeatures generated by hbm2java
 */
@Entity
@Table(name = "merchant_features"
      , catalog = "agilekartv2")
@XmlRootElement
public class MerchantFeatures implements java.io.Serializable
{
	private static final long serialVersionUID = -5945737996566300617L;
private String merchantFeaturesId;
   private FeatureOptions featureOptions;
   private Features features;
   private Merchant merchant;
   private String lastUpdateUserId;
   private Date lastUpdateTs;

   public MerchantFeatures()
   {
   }

   public MerchantFeatures(String merchantFeaturesId, FeatureOptions featureOptions, Features features, Merchant merchant)
   {
      this.merchantFeaturesId = merchantFeaturesId;
      this.featureOptions = featureOptions;
      this.features = features;
      this.merchant = merchant;
   }

   public MerchantFeatures(String merchantFeaturesId, FeatureOptions featureOptions, Features features, Merchant merchant, String lastUpdateUserId, Date lastUpdateTs)
   {
      this.merchantFeaturesId = merchantFeaturesId;
      this.featureOptions = featureOptions;
      this.features = features;
      this.merchant = merchant;
      this.lastUpdateUserId = lastUpdateUserId;
      this.lastUpdateTs = lastUpdateTs;
   }

   @Id
   @Column(name = "merchant_features_id", unique = true, nullable = false, length = 45)
   public String getMerchantFeaturesId()
   {
      return this.merchantFeaturesId;
   }

   public void setMerchantFeaturesId(String merchantFeaturesId)
   {
      this.merchantFeaturesId = merchantFeaturesId;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "feature_options_id", nullable = false)
   public FeatureOptions getFeatureOptions()
   {
      return this.featureOptions;
   }

   public void setFeatureOptions(FeatureOptions featureOptions)
   {
      this.featureOptions = featureOptions;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "feature_id", nullable = false)
   public Features getFeatures()
   {
      return this.features;
   }

   public void setFeatures(Features features)
   {
      this.features = features;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "merchant_id", nullable = false)
   public Merchant getMerchant()
   {
      return this.merchant;
   }

   public void setMerchant(Merchant merchant)
   {
      this.merchant = merchant;
   }

   @Column(name = "last_update_user_id", length = 45)
   public String getLastUpdateUserId()
   {
      return this.lastUpdateUserId;
   }

   public void setLastUpdateUserId(String lastUpdateUserId)
   {
      this.lastUpdateUserId = lastUpdateUserId;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "last_update_ts", length = 19)
   public Date getLastUpdateTs()
   {
      return this.lastUpdateTs;
   }

   public void setLastUpdateTs(Date lastUpdateTs)
   {
      this.lastUpdateTs = lastUpdateTs;
   }

}
