package org.AgileKartRest.model;

// Generated 12 Aug, 2015 11:27:47 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.xml.bind.annotation.XmlRootElement;

import org.codehaus.jackson.annotate.JsonIgnoreProperties;

/**
 * Merchant generated by hbm2java
 */
@Entity
@Table(name = "merchant"
      , catalog = "agilekartv2"
      , uniqueConstraints = @UniqueConstraint(columnNames = "merchant_name"))
@JsonIgnoreProperties({ "merchantFeatureses","merchantReviews","merchantCategories",
	"merchantAddresses","merchantPaymentGateways","loyaltyProgramMerchants","taxRuleMerchants",
	"userFavouriteses","products"})
@XmlRootElement
public class Merchant implements java.io.Serializable
{
	private static final long serialVersionUID = 2984677726743878078L;
	private String merchantId;
   private String merchantName;
   private String merchantEmail;
   private String merchantPassword;
   private String merchantPhoneNo;
   private Boolean merchantEmailVerified;
   private String merchantVerificationCode;
   private Integer minOrder;
   private Integer deliveryTime;
   private Integer merchantRating;
   private String lastUpdateUserId;
   private Date lastUpdateTs;
   private Set<MerchantFeatures> merchantFeatureses = new HashSet<MerchantFeatures>(0);
   private Set<Offer> offers = new HashSet<Offer>(0);
   private Set<MerchantReview> merchantReviews = new HashSet<MerchantReview>(0);
   private Set<MerchantCategory> merchantCategories = new HashSet<MerchantCategory>(0);
   private Set<MerchantAddress> merchantAddresses = new HashSet<MerchantAddress>(0);
   private Set<MerchantPaymentGateway> merchantPaymentGateways = new HashSet<MerchantPaymentGateway>(0);
   private Set<LoyaltyProgramMerchant> loyaltyProgramMerchants = new HashSet<LoyaltyProgramMerchant>(0);
   private Set<TaxRuleMerchant> taxRuleMerchants = new HashSet<TaxRuleMerchant>(0);
   private Set<UserFavourites> userFavouriteses = new HashSet<UserFavourites>(0);
   private Set<Product> products = new HashSet<Product>(0);

   public Merchant()
   {
   }

   public Merchant(String merchantId, String merchantName, String merchantEmail, String merchantPassword)
   {
      this.merchantId = merchantId;
      this.merchantName = merchantName;
      this.merchantEmail = merchantEmail;
      this.merchantPassword = merchantPassword;
   }

   public Merchant(String merchantId, String merchantName, String merchantEmail, String merchantPassword, String merchantPhoneNo, Boolean merchantEmailVerified, String merchantVerificationCode, Integer minOrder, Integer deliveryTime, Integer merchantRating, String lastUpdateUserId, Date lastUpdateTs, Set<MerchantFeatures> merchantFeatureses, Set<Offer> offers, Set<MerchantReview> merchantReviews, Set<MerchantCategory> merchantCategories, Set<MerchantAddress> merchantAddresses, Set<MerchantPaymentGateway> merchantPaymentGateways, Set<LoyaltyProgramMerchant> loyaltyProgramMerchants, Set<TaxRuleMerchant> taxRuleMerchants, Set<UserFavourites> userFavouriteses, Set<Product> products)
   {
      this.merchantId = merchantId;
      this.merchantName = merchantName;
      this.merchantEmail = merchantEmail;
      this.merchantPassword = merchantPassword;
      this.merchantPhoneNo = merchantPhoneNo;
      this.merchantEmailVerified = merchantEmailVerified;
      this.merchantVerificationCode = merchantVerificationCode;
      this.minOrder = minOrder;
      this.deliveryTime = deliveryTime;
      this.merchantRating = merchantRating;
      this.lastUpdateUserId = lastUpdateUserId;
      this.lastUpdateTs = lastUpdateTs;
      this.merchantFeatureses = merchantFeatureses;
      this.offers = offers;
      this.merchantReviews = merchantReviews;
      this.merchantCategories = merchantCategories;
      this.merchantAddresses = merchantAddresses;
      this.merchantPaymentGateways = merchantPaymentGateways;
      this.loyaltyProgramMerchants = loyaltyProgramMerchants;
      this.taxRuleMerchants = taxRuleMerchants;
      this.userFavouriteses = userFavouriteses;
      this.products = products;
   }

   @Id
   @Column(name = "merchant_id", unique = true, nullable = false, length = 45)
   public String getMerchantId()
   {
      return this.merchantId;
   }

   public void setMerchantId(String merchantId)
   {
      this.merchantId = merchantId;
   }

   @Column(name = "merchant_name", unique = true, nullable = false, length = 50)
   public String getMerchantName()
   {
      return this.merchantName;
   }

   public void setMerchantName(String merchantName)
   {
      this.merchantName = merchantName;
   }

   @Column(name = "merchant_email", nullable = false, length = 500)
   public String getMerchantEmail()
   {
      return this.merchantEmail;
   }

   public void setMerchantEmail(String merchantEmail)
   {
      this.merchantEmail = merchantEmail;
   }

   @Column(name = "merchant_password", nullable = false, length = 45)
   public String getMerchantPassword()
   {
      return this.merchantPassword;
   }

   public void setMerchantPassword(String merchantPassword)
   {
      this.merchantPassword = merchantPassword;
   }

   @Column(name = "merchant_phone_no", length = 15)
   public String getMerchantPhoneNo()
   {
      return this.merchantPhoneNo;
   }

   public void setMerchantPhoneNo(String merchantPhoneNo)
   {
      this.merchantPhoneNo = merchantPhoneNo;
   }

   @Column(name = "merchant_email_verified",columnDefinition = "BIT")
   public Boolean getMerchantEmailVerified()
   {
      return this.merchantEmailVerified;
   }

   public void setMerchantEmailVerified(Boolean merchantEmailVerified)
   {
      this.merchantEmailVerified = merchantEmailVerified;
   }

   @Column(name = "merchant_verification_code", length = 20)
   public String getMerchantVerificationCode()
   {
      return this.merchantVerificationCode;
   }

   public void setMerchantVerificationCode(String merchantVerificationCode)
   {
      this.merchantVerificationCode = merchantVerificationCode;
   }

   @Column(name = "min_order")
   public Integer getMinOrder()
   {
      return this.minOrder;
   }

   public void setMinOrder(Integer minOrder)
   {
      this.minOrder = minOrder;
   }

   @Column(name = "delivery_time")
   public Integer getDeliveryTime()
   {
      return this.deliveryTime;
   }

   public void setDeliveryTime(Integer deliveryTime)
   {
      this.deliveryTime = deliveryTime;
   }

   @Column(name = "merchant_rating")
   public Integer getMerchantRating()
   {
      return this.merchantRating;
   }

   public void setMerchantRating(Integer merchantRating)
   {
      this.merchantRating = merchantRating;
   }

   @Column(name = "last_update_user_id", length = 45)
   public String getLastUpdateUserId()
   {
      return this.lastUpdateUserId;
   }

   public void setLastUpdateUserId(String lastUpdateUserId)
   {
      this.lastUpdateUserId = lastUpdateUserId;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "last_update_ts", length = 19)
   public Date getLastUpdateTs()
   {
      return this.lastUpdateTs;
   }

   public void setLastUpdateTs(Date lastUpdateTs)
   {
      this.lastUpdateTs = lastUpdateTs;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "merchant")
   public Set<MerchantFeatures> getMerchantFeatureses()
   {
      return this.merchantFeatureses;
   }

   public void setMerchantFeatureses(Set<MerchantFeatures> merchantFeatureses)
   {
      this.merchantFeatureses = merchantFeatureses;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "merchant")
   public Set<Offer> getOffers()
   {
      return this.offers;
   }

   public void setOffers(Set<Offer> offers)
   {
      this.offers = offers;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "merchant")
   public Set<MerchantReview> getMerchantReviews()
   {
      return this.merchantReviews;
   }

   public void setMerchantReviews(Set<MerchantReview> merchantReviews)
   {
      this.merchantReviews = merchantReviews;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "merchant")
   public Set<MerchantCategory> getMerchantCategories()
   {
      return this.merchantCategories;
   }

   public void setMerchantCategories(Set<MerchantCategory> merchantCategories)
   {
      this.merchantCategories = merchantCategories;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "merchant")
   public Set<MerchantAddress> getMerchantAddresses()
   {
      return this.merchantAddresses;
   }

   public void setMerchantAddresses(Set<MerchantAddress> merchantAddresses)
   {
      this.merchantAddresses = merchantAddresses;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "merchant")
   public Set<MerchantPaymentGateway> getMerchantPaymentGateways()
   {
      return this.merchantPaymentGateways;
   }

   public void setMerchantPaymentGateways(Set<MerchantPaymentGateway> merchantPaymentGateways)
   {
      this.merchantPaymentGateways = merchantPaymentGateways;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "merchant")
   public Set<LoyaltyProgramMerchant> getLoyaltyProgramMerchants()
   {
      return this.loyaltyProgramMerchants;
   }

   public void setLoyaltyProgramMerchants(Set<LoyaltyProgramMerchant> loyaltyProgramMerchants)
   {
      this.loyaltyProgramMerchants = loyaltyProgramMerchants;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "merchant")
   public Set<TaxRuleMerchant> getTaxRuleMerchants()
   {
      return this.taxRuleMerchants;
   }

   public void setTaxRuleMerchants(Set<TaxRuleMerchant> taxRuleMerchants)
   {
      this.taxRuleMerchants = taxRuleMerchants;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "merchant")
   public Set<UserFavourites> getUserFavouriteses()
   {
      return this.userFavouriteses;
   }

   public void setUserFavouriteses(Set<UserFavourites> userFavouriteses)
   {
      this.userFavouriteses = userFavouriteses;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "merchant")
   public Set<Product> getProducts()
   {
      return this.products;
   }

   public void setProducts(Set<Product> products)
   {
      this.products = products;
   }

}
