package org.AgileKartRest.model;

// Generated 12 Aug, 2015 11:27:47 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Offer generated by hbm2java
 */
@Entity
@Table(name = "offer"
      , catalog = "agilekartv2")
@XmlRootElement
public class Offer implements java.io.Serializable
{

   /**
	 * 
	 */
	private static final long serialVersionUID = -9085358038938584003L;
private String offerId;
   private Merchant merchant;
   private Product product;
   private String offerName;
   private Integer offerDiscountPct;
   private Date offerStartDate;
   private Date offerEndDate;
   private Integer offerMaxCount;
   private String lastUpdateUserId;
   private Date lastUpdateTs;

   public Offer()
   {
   }

   public Offer(String offerId, String offerName)
   {
      this.offerId = offerId;
      this.offerName = offerName;
   }

   public Offer(String offerId, Merchant merchant, Product product, String offerName, Integer offerDiscountPct, Date offerStartDate, Date offerEndDate, Integer offerMaxCount, String lastUpdateUserId, Date lastUpdateTs)
   {
      this.offerId = offerId;
      this.merchant = merchant;
      this.product = product;
      this.offerName = offerName;
      this.offerDiscountPct = offerDiscountPct;
      this.offerStartDate = offerStartDate;
      this.offerEndDate = offerEndDate;
      this.offerMaxCount = offerMaxCount;
      this.lastUpdateUserId = lastUpdateUserId;
      this.lastUpdateTs = lastUpdateTs;
   }

   @Id
   @Column(name = "offer_id", unique = true, nullable = false, length = 45)
   public String getOfferId()
   {
      return this.offerId;
   }

   public void setOfferId(String offerId)
   {
      this.offerId = offerId;
   }

   @ManyToOne(fetch = FetchType.EAGER)
   @JoinColumn(name = "merchant_id")
   public Merchant getMerchant()
   {
      return this.merchant;
   }

   public void setMerchant(Merchant merchant)
   {
      this.merchant = merchant;
   }

   @ManyToOne(fetch = FetchType.EAGER)
   @JoinColumn(name = "product_id")
   public Product getProduct()
   {
      return this.product;
   }

   public void setProduct(Product product)
   {
      this.product = product;
   }

   @Column(name = "offer_name", nullable = false, length = 45)
   public String getOfferName()
   {
      return this.offerName;
   }

   public void setOfferName(String offerName)
   {
      this.offerName = offerName;
   }

   @Column(name = "offer_discount_pct")
   public Integer getOfferDiscountPct()
   {
      return this.offerDiscountPct;
   }

   public void setOfferDiscountPct(Integer offerDiscountPct)
   {
      this.offerDiscountPct = offerDiscountPct;
   }

   @Temporal(TemporalType.DATE)
   @Column(name = "offer_start_date", length = 10)
   public Date getOfferStartDate()
   {
      return this.offerStartDate;
   }

   public void setOfferStartDate(Date offerStartDate)
   {
      this.offerStartDate = offerStartDate;
   }

   @Temporal(TemporalType.DATE)
   @Column(name = "offer_end_date", length = 10)
   public Date getOfferEndDate()
   {
      return this.offerEndDate;
   }

   public void setOfferEndDate(Date offerEndDate)
   {
      this.offerEndDate = offerEndDate;
   }

   @Column(name = "offer_max_count")
   public Integer getOfferMaxCount()
   {
      return this.offerMaxCount;
   }

   public void setOfferMaxCount(Integer offerMaxCount)
   {
      this.offerMaxCount = offerMaxCount;
   }

   @Column(name = "last_update_user_id", length = 45)
   public String getLastUpdateUserId()
   {
      return this.lastUpdateUserId;
   }

   public void setLastUpdateUserId(String lastUpdateUserId)
   {
      this.lastUpdateUserId = lastUpdateUserId;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "last_update_ts", length = 19)
   public Date getLastUpdateTs()
   {
      return this.lastUpdateTs;
   }

   public void setLastUpdateTs(Date lastUpdateTs)
   {
      this.lastUpdateTs = lastUpdateTs;
   }

}
