package org.AgileKartRest.model;

// Generated 12 Aug, 2015 11:27:47 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.xml.bind.annotation.XmlRootElement;

import org.codehaus.jackson.annotate.JsonIgnoreProperties;

/**
 * Options generated by hbm2java
 */
@Entity
@Table(name = "options"
      , catalog = "agilekartv2"
      , uniqueConstraints = @UniqueConstraint(columnNames = { "option_name", "option_group_id" }))
@JsonIgnoreProperties({ "productOptions"})
@XmlRootElement
public class Options implements java.io.Serializable
{
	private static final long serialVersionUID = -6412552062083940744L;
private String optionId;
   private OptionGroups optionGroups;
   private String optionName;
   private String lastUpdateUserId;
   private Date lastUpdateTs;
   private Set<ProductOption> productOptions = new HashSet<ProductOption>(0);

   public Options()
   {
   }

   public Options(String optionId, OptionGroups optionGroups, String optionName)
   {
      this.optionId = optionId;
      this.optionGroups = optionGroups;
      this.optionName = optionName;
   }

   public Options(String optionId, OptionGroups optionGroups, String optionName, String lastUpdateUserId, Date lastUpdateTs, Set<ProductOption> productOptions)
   {
      this.optionId = optionId;
      this.optionGroups = optionGroups;
      this.optionName = optionName;
      this.lastUpdateUserId = lastUpdateUserId;
      this.lastUpdateTs = lastUpdateTs;
      this.productOptions = productOptions;
   }

   @Id
   @Column(name = "option_id", unique = true, nullable = false, length = 45)
   public String getOptionId()
   {
      return this.optionId;
   }

   public void setOptionId(String optionId)
   {
      this.optionId = optionId;
   }

   @ManyToOne(fetch = FetchType.EAGER)
   @JoinColumn(name = "option_group_id", nullable = false)
   public OptionGroups getOptionGroups()
   {
      return this.optionGroups;
   }

   public void setOptionGroups(OptionGroups optionGroups)
   {
      this.optionGroups = optionGroups;
   }

   @Column(name = "option_name", nullable = false, length = 50)
   public String getOptionName()
   {
      return this.optionName;
   }

   public void setOptionName(String optionName)
   {
      this.optionName = optionName;
   }

   @Column(name = "last_update_user_id", length = 45)
   public String getLastUpdateUserId()
   {
      return this.lastUpdateUserId;
   }

   public void setLastUpdateUserId(String lastUpdateUserId)
   {
      this.lastUpdateUserId = lastUpdateUserId;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "last_update_ts", length = 19)
   public Date getLastUpdateTs()
   {
      return this.lastUpdateTs;
   }

   public void setLastUpdateTs(Date lastUpdateTs)
   {
      this.lastUpdateTs = lastUpdateTs;
   }

   @OneToMany(fetch = FetchType.EAGER, mappedBy = "options")
   public Set<ProductOption> getProductOptions()
   {
      return this.productOptions;
   }

   public void setProductOptions(Set<ProductOption> productOptions)
   {
      this.productOptions = productOptions;
   }

}
