package org.AgileKartRest.model;

// Generated 12 Aug, 2015 11:27:47 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;

import org.codehaus.jackson.annotate.JsonIgnoreProperties;

/**
 * OrderStatusDesc generated by hbm2java
 */
@Entity
@Table(name = "order_status_desc"
      , catalog = "agilekartv2")
@JsonIgnoreProperties({ "orderStatuses"})
@XmlRootElement
public class OrderStatusDesc implements java.io.Serializable
{

   /**
	 * 
	 */
	private static final long serialVersionUID = 2052489817745281904L;
private String orderStatusDescId;
   private String orderStatusDescText;
   private String lastUpdateUserId;
   private Date lastUpdateTs;
   private Set<OrderStatus> orderStatuses = new HashSet<OrderStatus>(0);

   public OrderStatusDesc()
   {
   }

   public OrderStatusDesc(String orderStatusDescId)
   {
      this.orderStatusDescId = orderStatusDescId;
   }

   public OrderStatusDesc(String orderStatusDescId, String orderStatusDescText, String lastUpdateUserId, Date lastUpdateTs, Set<OrderStatus> orderStatuses)
   {
      this.orderStatusDescId = orderStatusDescId;
      this.orderStatusDescText = orderStatusDescText;
      this.lastUpdateUserId = lastUpdateUserId;
      this.lastUpdateTs = lastUpdateTs;
      this.orderStatuses = orderStatuses;
   }

   @Id
   @Column(name = "order_status_desc_id", unique = true, nullable = false, length = 45)
   public String getOrderStatusDescId()
   {
      return this.orderStatusDescId;
   }

   public void setOrderStatusDescId(String orderStatusDescId)
   {
      this.orderStatusDescId = orderStatusDescId;
   }

   @Column(name = "order_status_desc_text", length = 500)
   public String getOrderStatusDescText()
   {
      return this.orderStatusDescText;
   }

   public void setOrderStatusDescText(String orderStatusDescText)
   {
      this.orderStatusDescText = orderStatusDescText;
   }

   @Column(name = "last_update_user_id", length = 45)
   public String getLastUpdateUserId()
   {
      return this.lastUpdateUserId;
   }

   public void setLastUpdateUserId(String lastUpdateUserId)
   {
      this.lastUpdateUserId = lastUpdateUserId;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "last_update_ts", length = 19)
   public Date getLastUpdateTs()
   {
      return this.lastUpdateTs;
   }

   public void setLastUpdateTs(Date lastUpdateTs)
   {
      this.lastUpdateTs = lastUpdateTs;
   }

   @OneToMany(fetch = FetchType.EAGER, mappedBy = "orderStatusDesc")
   public Set<OrderStatus> getOrderStatuses()
   {
      return this.orderStatuses;
   }

   public void setOrderStatuses(Set<OrderStatus> orderStatuses)
   {
      this.orderStatuses = orderStatuses;
   }

}
