package org.AgileKartRest.model;

// Generated 12 Aug, 2015 11:27:47 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * OrderDetails generated by hbm2java
 */
@Entity
@Table(name = "order_details"
      , catalog = "agilekartv2")
@XmlRootElement
public class OrderDetails implements java.io.Serializable
{
	private static final long serialVersionUID = 4597847902259687296L;
private String detailId;
   private Orders orders;
   private Product product;
   private String detailName;
   private float detailPrice;
   private int detailQuantity;
   private String lastUpdateUserId;
   private Date lastUpdateTs;

   public OrderDetails()
   {
   }

   public OrderDetails(String detailId, Orders orders, Product product, String detailName, float detailPrice, int detailQuantity)
   {
      this.detailId = detailId;
      this.orders = orders;
      this.product = product;
      this.detailName = detailName;
      this.detailPrice = detailPrice;
      this.detailQuantity = detailQuantity;
   }

   public OrderDetails(String detailId, Orders orders, Product product, String detailName, float detailPrice, int detailQuantity, String lastUpdateUserId, Date lastUpdateTs)
   {
      this.detailId = detailId;
      this.orders = orders;
      this.product = product;
      this.detailName = detailName;
      this.detailPrice = detailPrice;
      this.detailQuantity = detailQuantity;
      this.lastUpdateUserId = lastUpdateUserId;
      this.lastUpdateTs = lastUpdateTs;
   }

   @Id
   @Column(name = "detail_id", unique = true, nullable = false, length = 45)
   public String getDetailId()
   {
      return this.detailId;
   }

   public void setDetailId(String detailId)
   {
      this.detailId = detailId;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "order_id", nullable = false)
   public Orders getOrders()
   {
      return this.orders;
   }

   public void setOrders(Orders orders)
   {
      this.orders = orders;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "product_id", nullable = false)
   public Product getProduct()
   {
      return this.product;
   }

   public void setProduct(Product product)
   {
      this.product = product;
   }

   @Column(name = "detail_name", nullable = false, length = 250)
   public String getDetailName()
   {
      return this.detailName;
   }

   public void setDetailName(String detailName)
   {
      this.detailName = detailName;
   }

   @Column(name = "detail_price", nullable = false, precision = 12, scale = 0)
   public float getDetailPrice()
   {
      return this.detailPrice;
   }

   public void setDetailPrice(float detailPrice)
   {
      this.detailPrice = detailPrice;
   }

   @Column(name = "detail_quantity", nullable = false)
   public int getDetailQuantity()
   {
      return this.detailQuantity;
   }

   public void setDetailQuantity(int detailQuantity)
   {
      this.detailQuantity = detailQuantity;
   }

   @Column(name = "last_update_user_id", length = 45)
   public String getLastUpdateUserId()
   {
      return this.lastUpdateUserId;
   }

   public void setLastUpdateUserId(String lastUpdateUserId)
   {
      this.lastUpdateUserId = lastUpdateUserId;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "last_update_ts", length = 19)
   public Date getLastUpdateTs()
   {
      return this.lastUpdateTs;
   }

   public void setLastUpdateTs(Date lastUpdateTs)
   {
      this.lastUpdateTs = lastUpdateTs;
   }

}
