package org.AgileKartRest.model;

// Generated 12 Aug, 2015 11:27:47 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * ProductCategory generated by hbm2java
 */
@Entity
@Table(name = "product_category"
      , catalog = "agilekartv2")
@XmlRootElement
public class ProductCategory implements java.io.Serializable
{
	private static final long serialVersionUID = -2473317143244122393L;
private String productCategoryId;
   private Category category;
   private Product product;
   private String lastUpdateUserId;
   private Date lastUpdateTs;

   public ProductCategory()
   {
   }

   public ProductCategory(String productCategoryId, Category category, Product product)
   {
      this.productCategoryId = productCategoryId;
      this.category = category;
      this.product = product;
   }

   public ProductCategory(String productCategoryId, Category category, Product product, String lastUpdateUserId, Date lastUpdateTs)
   {
      this.productCategoryId = productCategoryId;
      this.category = category;
      this.product = product;
      this.lastUpdateUserId = lastUpdateUserId;
      this.lastUpdateTs = lastUpdateTs;
   }

   @Id
   @Column(name = "product_category_id", unique = true, nullable = false, length = 45)
   public String getProductCategoryId()
   {
      return this.productCategoryId;
   }

   public void setProductCategoryId(String productCategoryId)
   {
      this.productCategoryId = productCategoryId;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "category_id", nullable = false)
   public Category getCategory()
   {
      return this.category;
   }

   public void setCategory(Category category)
   {
      this.category = category;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "product_id", nullable = false)
   public Product getProduct()
   {
      return this.product;
   }

   public void setProduct(Product product)
   {
      this.product = product;
   }

   @Column(name = "last_update_user_id", length = 45)
   public String getLastUpdateUserId()
   {
      return this.lastUpdateUserId;
   }

   public void setLastUpdateUserId(String lastUpdateUserId)
   {
      this.lastUpdateUserId = lastUpdateUserId;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "last_update_ts", length = 19)
   public Date getLastUpdateTs()
   {
      return this.lastUpdateTs;
   }

   public void setLastUpdateTs(Date lastUpdateTs)
   {
      this.lastUpdateTs = lastUpdateTs;
   }

}
