package org.AgileKartRest.model;

// Generated 12 Aug, 2015 11:27:47 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * ProductOption generated by hbm2java
 */
@Entity
@Table(name = "product_option"
      , catalog = "agilekartv2")
@XmlRootElement
public class ProductOption implements java.io.Serializable
{
	private static final long serialVersionUID = 7060805588283437857L;
private String productOptionId;
   private OptionGroups optionGroups;
   private Options options;
   private Product product;
   private String lastUpdateUserId;
   private Date lastUpdateTs;

   public ProductOption()
   {
   }

   public ProductOption(String productOptionId, OptionGroups optionGroups, Options options, Product product)
   {
      this.productOptionId = productOptionId;
      this.optionGroups = optionGroups;
      this.options = options;
      this.product = product;
   }

   public ProductOption(String productOptionId, OptionGroups optionGroups, Options options, Product product, String lastUpdateUserId, Date lastUpdateTs)
   {
      this.productOptionId = productOptionId;
      this.optionGroups = optionGroups;
      this.options = options;
      this.product = product;
      this.lastUpdateUserId = lastUpdateUserId;
      this.lastUpdateTs = lastUpdateTs;
   }

   @Id
   @Column(name = "product_option_id", unique = true, nullable = false, length = 45)
   public String getProductOptionId()
   {
      return this.productOptionId;
   }

   public void setProductOptionId(String productOptionId)
   {
      this.productOptionId = productOptionId;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "option_group_id", nullable = false)
   public OptionGroups getOptionGroups()
   {
      return this.optionGroups;
   }

   public void setOptionGroups(OptionGroups optionGroups)
   {
      this.optionGroups = optionGroups;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "option_id", nullable = false)
   public Options getOptions()
   {
      return this.options;
   }

   public void setOptions(Options options)
   {
      this.options = options;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "product_id", nullable = false)
   public Product getProduct()
   {
      return this.product;
   }

   public void setProduct(Product product)
   {
      this.product = product;
   }

   @Column(name = "last_update_user_id", length = 45)
   public String getLastUpdateUserId()
   {
      return this.lastUpdateUserId;
   }

   public void setLastUpdateUserId(String lastUpdateUserId)
   {
      this.lastUpdateUserId = lastUpdateUserId;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "last_update_ts", length = 19)
   public Date getLastUpdateTs()
   {
      return this.lastUpdateTs;
   }

   public void setLastUpdateTs(Date lastUpdateTs)
   {
      this.lastUpdateTs = lastUpdateTs;
   }

}
