package org.AgileKartRest.model;

// Generated 12 Aug, 2015 11:27:47 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * SequenceKeyTable generated by hbm2java
 */
@Entity
@Table(name = "sequence_key_table"
      , catalog = "agilekartv2")
@XmlRootElement
public class SequenceKeyTable implements java.io.Serializable
{
	private static final long serialVersionUID = 7599027609299779753L;
private int tableId;
   private String tableName;
   private String keyPrefix;
   private int maxCount;

   public SequenceKeyTable()
   {
   }

   public SequenceKeyTable(int tableId, String tableName, String keyPrefix, int maxCount)
   {
      this.tableId = tableId;
      this.tableName = tableName;
      this.keyPrefix = keyPrefix;
      this.maxCount = maxCount;
   }

   @Id
   @Column(name = "table_Id", unique = true, nullable = false)
   public int getTableId()
   {
      return this.tableId;
   }

   public void setTableId(int tableId)
   {
      this.tableId = tableId;
   }

   @Column(name = "table_Name", nullable = false, length = 45)
   public String getTableName()
   {
      return this.tableName;
   }

   public void setTableName(String tableName)
   {
      this.tableName = tableName;
   }

   @Column(name = "key_Prefix", nullable = false, length = 45)
   public String getKeyPrefix()
   {
      return this.keyPrefix;
   }

   public void setKeyPrefix(String keyPrefix)
   {
      this.keyPrefix = keyPrefix;
   }

   @Column(name = "max_Count", nullable = false)
   public int getMaxCount()
   {
      return this.maxCount;
   }

   public void setMaxCount(int maxCount)
   {
      this.maxCount = maxCount;
   }

}
