package org.AgileKartRest.model;

// Generated 12 Aug, 2015 11:27:47 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;

import org.codehaus.jackson.annotate.JsonIgnoreProperties;

/**
 * TaxRule generated by hbm2java
 */
@Entity
@Table(name = "tax_rule"
      , catalog = "agilekartv2")
@JsonIgnoreProperties({ "taxRuleMerchants"})
@XmlRootElement
public class TaxRule implements java.io.Serializable
{
	private static final long serialVersionUID = -7391137720118564133L;
private String taxRuleId;
   private Tax tax;
   private String taxRuleName;
   private String stateCd;
   private String countryCd;
   private String lastUpdateUserId;
   private Date lastUpdateTs;
   private Set<TaxRuleMerchant> taxRuleMerchants = new HashSet<TaxRuleMerchant>(0);

   public TaxRule()
   {
   }

   public TaxRule(String taxRuleId, Tax tax)
   {
      this.taxRuleId = taxRuleId;
      this.tax = tax;
   }

   public TaxRule(String taxRuleId, Tax tax, String taxRuleName, String stateCd, String countryCd, String lastUpdateUserId, Date lastUpdateTs, Set<TaxRuleMerchant> taxRuleMerchants)
   {
      this.taxRuleId = taxRuleId;
      this.tax = tax;
      this.taxRuleName = taxRuleName;
      this.stateCd = stateCd;
      this.countryCd = countryCd;
      this.lastUpdateUserId = lastUpdateUserId;
      this.lastUpdateTs = lastUpdateTs;
      this.taxRuleMerchants = taxRuleMerchants;
   }

   @Id
   @Column(name = "tax_rule_id", unique = true, nullable = false, length = 45)
   public String getTaxRuleId()
   {
      return this.taxRuleId;
   }

   public void setTaxRuleId(String taxRuleId)
   {
      this.taxRuleId = taxRuleId;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "tax_id", nullable = false)
   public Tax getTax()
   {
      return this.tax;
   }

   public void setTax(Tax tax)
   {
      this.tax = tax;
   }

   @Column(name = "tax_rule_name", length = 45)
   public String getTaxRuleName()
   {
      return this.taxRuleName;
   }

   public void setTaxRuleName(String taxRuleName)
   {
      this.taxRuleName = taxRuleName;
   }

   @Column(name = "state_cd", length = 45)
   public String getStateCd()
   {
      return this.stateCd;
   }

   public void setStateCd(String stateCd)
   {
      this.stateCd = stateCd;
   }

   @Column(name = "country_cd", length = 45)
   public String getCountryCd()
   {
      return this.countryCd;
   }

   public void setCountryCd(String countryCd)
   {
      this.countryCd = countryCd;
   }

   @Column(name = "last_update_user_id", length = 45)
   public String getLastUpdateUserId()
   {
      return this.lastUpdateUserId;
   }

   public void setLastUpdateUserId(String lastUpdateUserId)
   {
      this.lastUpdateUserId = lastUpdateUserId;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "last_update_ts", length = 19)
   public Date getLastUpdateTs()
   {
      return this.lastUpdateTs;
   }

   public void setLastUpdateTs(Date lastUpdateTs)
   {
      this.lastUpdateTs = lastUpdateTs;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "taxRule")
   public Set<TaxRuleMerchant> getTaxRuleMerchants()
   {
      return this.taxRuleMerchants;
   }

   public void setTaxRuleMerchants(Set<TaxRuleMerchant> taxRuleMerchants)
   {
      this.taxRuleMerchants = taxRuleMerchants;
   }

}
