package org.AgileKartRest.model;

// Generated 12 Aug, 2015 11:27:47 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * TaxRuleMerchant generated by hbm2java
 */
@Entity
@Table(name = "tax_rule_merchant"
      , catalog = "agilekartv2")
@XmlRootElement
public class TaxRuleMerchant implements java.io.Serializable
{
	private static final long serialVersionUID = 5403662249466568601L;
private String taxRuleMerchantId;
   private Merchant merchant;
   private TaxRule taxRule;
   private String lastUpdateUserId;
   private Date lastUpdateTs;

   public TaxRuleMerchant()
   {
   }

   public TaxRuleMerchant(String taxRuleMerchantId, Merchant merchant, TaxRule taxRule)
   {
      this.taxRuleMerchantId = taxRuleMerchantId;
      this.merchant = merchant;
      this.taxRule = taxRule;
   }

   public TaxRuleMerchant(String taxRuleMerchantId, Merchant merchant, TaxRule taxRule, String lastUpdateUserId, Date lastUpdateTs)
   {
      this.taxRuleMerchantId = taxRuleMerchantId;
      this.merchant = merchant;
      this.taxRule = taxRule;
      this.lastUpdateUserId = lastUpdateUserId;
      this.lastUpdateTs = lastUpdateTs;
   }

   @Id
   @Column(name = "tax_rule_merchant_id", unique = true, nullable = false, length = 45)
   public String getTaxRuleMerchantId()
   {
      return this.taxRuleMerchantId;
   }

   public void setTaxRuleMerchantId(String taxRuleMerchantId)
   {
      this.taxRuleMerchantId = taxRuleMerchantId;
   }

   @ManyToOne(fetch = FetchType.EAGER)
   @JoinColumn(name = "merchant_id", nullable = false)
   public Merchant getMerchant()
   {
      return this.merchant;
   }

   public void setMerchant(Merchant merchant)
   {
      this.merchant = merchant;
   }

   @ManyToOne(fetch = FetchType.EAGER)
   @JoinColumn(name = "tax_rule_id", nullable = false)
   public TaxRule getTaxRule()
   {
      return this.taxRule;
   }

   public void setTaxRule(TaxRule taxRule)
   {
      this.taxRule = taxRule;
   }

   @Column(name = "last_update_user_id", length = 45)
   public String getLastUpdateUserId()
   {
      return this.lastUpdateUserId;
   }

   public void setLastUpdateUserId(String lastUpdateUserId)
   {
      this.lastUpdateUserId = lastUpdateUserId;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "last_update_ts", length = 19)
   public Date getLastUpdateTs()
   {
      return this.lastUpdateTs;
   }

   public void setLastUpdateTs(Date lastUpdateTs)
   {
      this.lastUpdateTs = lastUpdateTs;
   }

}
