package org.AgileKartRest.entity;

// Generated May 27, 2015 8:00:59 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * AkCategoryOptions generated by hbm2java
 */
@Entity
@Table(name = "ak_category_options"
      , catalog = "agilekart")
@XmlRootElement
public class AkCategoryOptions implements java.io.Serializable
{

   private int categoryOptionId;
   private AkOptionGroups akOptionGroups;
   private AkProductCategories akProductCategories;

   public AkCategoryOptions()
   {
   }

   public AkCategoryOptions(int categoryOptionId, AkOptionGroups akOptionGroups, AkProductCategories akProductCategories)
   {
      this.categoryOptionId = categoryOptionId;
      this.akOptionGroups = akOptionGroups;
      this.akProductCategories = akProductCategories;
   }

   @Id
   @Column(name = "category_option_id", unique = true, nullable = false)
   public int getCategoryOptionId()
   {
      return this.categoryOptionId;
   }

   public void setCategoryOptionId(int categoryOptionId)
   {
      this.categoryOptionId = categoryOptionId;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "option_group_id", nullable = false)
   public AkOptionGroups getAkOptionGroups()
   {
      return this.akOptionGroups;
   }

   public void setAkOptionGroups(AkOptionGroups akOptionGroups)
   {
      this.akOptionGroups = akOptionGroups;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "category_id", nullable = false)
   public AkProductCategories getAkProductCategories()
   {
      return this.akProductCategories;
   }

   public void setAkProductCategories(AkProductCategories akProductCategories)
   {
      this.akProductCategories = akProductCategories;
   }

}