package org.AgileKartRest.entity;

// Generated May 23, 2015 8:30:37 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.xml.bind.annotation.XmlRootElement;

import org.codehaus.jackson.annotate.JsonIgnoreProperties;

/**
 * AkOptions generated by hbm2java
 */
@Entity
@Table(name = "ak_options"
      , catalog = "agilekart"
      , uniqueConstraints = @UniqueConstraint(columnNames = { "option_name", "option_group_id" }))
@JsonIgnoreProperties({ "akProductOptionses"})
@XmlRootElement
public class AkOptions implements java.io.Serializable
{

   /**
	 * 
	 */
	private static final long serialVersionUID = -7963868387389368516L;
private Integer optionId;
   private AkOptionGroups akOptionGroups;
   private String optionName;
   private Set<AkProductOptions> akProductOptionses = new HashSet<AkProductOptions>(0);

   public AkOptions()
   {
   }

   public AkOptions(AkOptionGroups akOptionGroups, String optionName)
   {
      this.akOptionGroups = akOptionGroups;
      this.optionName = optionName;
   }

   public AkOptions(AkOptionGroups akOptionGroups, String optionName, Set<AkProductOptions> akProductOptionses)
   {
      this.akOptionGroups = akOptionGroups;
      this.optionName = optionName;
      this.akProductOptionses = akProductOptionses;
   }

   @Id
   @GeneratedValue(strategy = IDENTITY)
   @Column(name = "option_id", unique = true, nullable = false)
   public Integer getOptionId()
   {
      return this.optionId;
   }

   public void setOptionId(Integer optionId)
   {
      this.optionId = optionId;
   }

   @ManyToOne(fetch = FetchType.EAGER)
   @JoinColumn(name = "option_group_id", nullable = false)
   public AkOptionGroups getAkOptionGroups()
   {
      return this.akOptionGroups;
   }

   public void setAkOptionGroups(AkOptionGroups akOptionGroups)
   {
      this.akOptionGroups = akOptionGroups;
   }

   @Column(name = "option_name", nullable = false, length = 50)
   public String getOptionName()
   {
      return this.optionName;
   }

   public void setOptionName(String optionName)
   {
      this.optionName = optionName;
   }

   @OneToMany(fetch = FetchType.EAGER, mappedBy = "akOptions")
   public Set<AkProductOptions> getAkProductOptionses()
   {
      return this.akProductOptionses;
   }

   public void setAkProductOptionses(Set<AkProductOptions> akProductOptionses)
   {
      this.akProductOptionses = akProductOptionses;
   }

}
