package org.AgileKartRest.entity;

// Generated 21 Jun, 2015 11:28:57 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.xml.bind.annotation.XmlRootElement;

import org.codehaus.jackson.annotate.JsonIgnoreProperties;

/**
 * AkOptionGroups generated by hbm2java
 */
@Entity
@Table(name = "ak_option_groups"
      , catalog = "agilekart"
      , uniqueConstraints = @UniqueConstraint(columnNames = "option_group_desc"))
@JsonIgnoreProperties({ "akProductOptionses","akOptionses","akCategoryOptionses"})
@XmlRootElement
public class AkOptionGroups implements java.io.Serializable
{

   private Integer optionGroupId;
   private String optionGroupName;
   private String optionGroupDesc;
   private Set<AkOptions> akOptionses = new HashSet<AkOptions>(0);
   private Set<AkCategoryOptions> akCategoryOptionses = new HashSet<AkCategoryOptions>(0);
   private Set<AkProductOptions> akProductOptionses = new HashSet<AkProductOptions>(0);

   public AkOptionGroups()
   {
   }

   public AkOptionGroups(String optionGroupName, String optionGroupDesc)
   {
      this.optionGroupName = optionGroupName;
      this.optionGroupDesc = optionGroupDesc;
   }

   public AkOptionGroups(String optionGroupName, String optionGroupDesc, Set<AkOptions> akOptionses, Set<AkCategoryOptions> akCategoryOptionses, Set<AkProductOptions> akProductOptionses)
   {
      this.optionGroupName = optionGroupName;
      this.optionGroupDesc = optionGroupDesc;
      this.akOptionses = akOptionses;
      this.akCategoryOptionses = akCategoryOptionses;
      this.akProductOptionses = akProductOptionses;
   }

   @Id
   @GeneratedValue(strategy = IDENTITY)
   @Column(name = "option_group_id", unique = true, nullable = false)
   public Integer getOptionGroupId()
   {
      return this.optionGroupId;
   }

   public void setOptionGroupId(Integer optionGroupId)
   {
      this.optionGroupId = optionGroupId;
   }

   @Column(name = "option_group_name", nullable = false, length = 50)
   public String getOptionGroupName()
   {
      return this.optionGroupName;
   }

   public void setOptionGroupName(String optionGroupName)
   {
      this.optionGroupName = optionGroupName;
   }

   @Column(name = "option_group_desc", unique = true, nullable = false, length = 45)
   public String getOptionGroupDesc()
   {
      return this.optionGroupDesc;
   }

   public void setOptionGroupDesc(String optionGroupDesc)
   {
      this.optionGroupDesc = optionGroupDesc;
   }

   @OneToMany(fetch = FetchType.EAGER, mappedBy = "akOptionGroups")
   public Set<AkOptions> getAkOptionses()
   {
      return this.akOptionses;
   }

   public void setAkOptionses(Set<AkOptions> akOptionses)
   {
      this.akOptionses = akOptionses;
   }

   @OneToMany(fetch = FetchType.EAGER, mappedBy = "akOptionGroups")
   public Set<AkCategoryOptions> getAkCategoryOptionses()
   {
      return this.akCategoryOptionses;
   }

   public void setAkCategoryOptionses(Set<AkCategoryOptions> akCategoryOptionses)
   {
      this.akCategoryOptionses = akCategoryOptionses;
   }

   @OneToMany(fetch = FetchType.EAGER, mappedBy = "akOptionGroups")
   public Set<AkProductOptions> getAkProductOptionses()
   {
      return this.akProductOptionses;
   }

   public void setAkProductOptionses(Set<AkProductOptions> akProductOptionses)
   {
      this.akProductOptionses = akProductOptionses;
   }

}
