package org.AgileKartRest.entity;

// Generated 6 Jun, 2015 10:46:57 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;

import org.codehaus.jackson.annotate.JsonIgnoreProperties;

/**
 * AkUsers generated by hbm2java
 */
@Entity
@Table(name = "ak_users"
      , catalog = "agilekart")
@JsonIgnoreProperties({ "akUserAddresses", "akOrderses"})
@XmlRootElement
public class AkUsers implements java.io.Serializable
{

   /**
	 * 
	 */
	private static final long serialVersionUID = -8774541469867506078L;
private Integer userId;
   private String userEmail;
   private String userPassword;
   private String userFirstName;
   private String userLastName;
   private Boolean userEmailVerified;
   private Date userRegistrationDate;
   private String userVerificationCode;
   private String userIp;
   private Set<AkUserAddress> akUserAddresses = new HashSet<AkUserAddress>(0);
   private Set<AkOrders> akOrderses = new HashSet<AkOrders>(0);

   public AkUsers()
   {
   }

   public AkUsers(String userEmail, String userPassword, String userFirstName, String userLastName, Boolean userEmailVerified, Date userRegistrationDate, String userVerificationCode, String userIp, Set<AkUserAddress> akUserAddresses, Set<AkOrders> akOrderses)
   {
      this.userEmail = userEmail;
      this.userPassword = userPassword;
      this.userFirstName = userFirstName;
      this.userLastName = userLastName;
      this.userEmailVerified = userEmailVerified;
      this.userRegistrationDate = userRegistrationDate;
      this.userVerificationCode = userVerificationCode;
      this.userIp = userIp;
      this.akUserAddresses = akUserAddresses;
      this.akOrderses = akOrderses;
   }

   @Id
   @GeneratedValue(strategy = IDENTITY)
   @Column(name = "user_id", unique = true, nullable = false)
   public Integer getUserId()
   {
      return this.userId;
   }

   public void setUserId(Integer userId)
   {
      this.userId = userId;
   }

   @Column(name = "user_email", length = 500)
   public String getUserEmail()
   {
      return this.userEmail;
   }

   public void setUserEmail(String userEmail)
   {
      this.userEmail = userEmail;
   }

   @Column(name = "user_password", length = 500)
   public String getUserPassword()
   {
      return this.userPassword;
   }

   public void setUserPassword(String userPassword)
   {
      this.userPassword = userPassword;
   }

   @Column(name = "user_first_name", length = 50)
   public String getUserFirstName()
   {
      return this.userFirstName;
   }

   public void setUserFirstName(String userFirstName)
   {
      this.userFirstName = userFirstName;
   }

   @Column(name = "user_last_name", length = 50)
   public String getUserLastName()
   {
      return this.userLastName;
   }

   public void setUserLastName(String userLastName)
   {
      this.userLastName = userLastName;
   }

   @Column(name = "user_email_verified", columnDefinition = "BIT")
   public Boolean getUserEmailVerified()
   {
      return this.userEmailVerified;
   }

   public void setUserEmailVerified(Boolean userEmailVerified)
   {
      this.userEmailVerified = userEmailVerified;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "user_registration_date", length = 19)
   public Date getUserRegistrationDate()
   {
      return this.userRegistrationDate;
   }

   public void setUserRegistrationDate(Date userRegistrationDate)
   {
      this.userRegistrationDate = userRegistrationDate;
   }

   @Column(name = "user_verification_code", length = 20)
   public String getUserVerificationCode()
   {
      return this.userVerificationCode;
   }

   public void setUserVerificationCode(String userVerificationCode)
   {
      this.userVerificationCode = userVerificationCode;
   }

   @Column(name = "user_ip", length = 50)
   public String getUserIp()
   {
      return this.userIp;
   }

   public void setUserIp(String userIp)
   {
      this.userIp = userIp;
   }

   @OneToMany(fetch = FetchType.EAGER, mappedBy = "akUsers")
   public Set<AkUserAddress> getAkUserAddresses()
   {
      return this.akUserAddresses;
   }

   public void setAkUserAddresses(Set<AkUserAddress> akUserAddresses)
   {
      this.akUserAddresses = akUserAddresses;
   }

   @OneToMany(fetch = FetchType.EAGER, mappedBy = "akUsers")
   public Set<AkOrders> getAkOrderses()
   {
      return this.akOrderses;
   }

   public void setAkOrderses(Set<AkOrders> akOrderses)
   {
      this.akOrderses = akOrderses;
   }

}
