package org.agilekartV2.model;

// Generated Jul 16, 2015 1:41:40 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * CategoryOptions generated by hbm2java
 */
@Entity
@Table(name = "category_options"
      , catalog = "agilekartV2")
@XmlRootElement
public class CategoryOptions implements java.io.Serializable
{

   private String categoryOptionsId;
   private String categoryId;
   private String optionGroupId;
   private String lastUpdateUserId;
   private Date lastUpdateTs;

   public CategoryOptions()
   {
   }

   public CategoryOptions(String categoryOptionsId)
   {
      this.categoryOptionsId = categoryOptionsId;
   }

   public CategoryOptions(String categoryOptionsId, String categoryId, String optionGroupId, String lastUpdateUserId, Date lastUpdateTs)
   {
      this.categoryOptionsId = categoryOptionsId;
      this.categoryId = categoryId;
      this.optionGroupId = optionGroupId;
      this.lastUpdateUserId = lastUpdateUserId;
      this.lastUpdateTs = lastUpdateTs;
   }

   @Id
   @Column(name = "category_options_id", unique = true, nullable = false, length = 45)
   public String getCategoryOptionsId()
   {
      return this.categoryOptionsId;
   }

   public void setCategoryOptionsId(String categoryOptionsId)
   {
      this.categoryOptionsId = categoryOptionsId;
   }

   @Column(name = "category_id", length = 45)
   public String getCategoryId()
   {
      return this.categoryId;
   }

   public void setCategoryId(String categoryId)
   {
      this.categoryId = categoryId;
   }

   @Column(name = "option_group_id", length = 45)
   public String getOptionGroupId()
   {
      return this.optionGroupId;
   }

   public void setOptionGroupId(String optionGroupId)
   {
      this.optionGroupId = optionGroupId;
   }

   @Column(name = "last_update_user_id", length = 45)
   public String getLastUpdateUserId()
   {
      return this.lastUpdateUserId;
   }

   public void setLastUpdateUserId(String lastUpdateUserId)
   {
      this.lastUpdateUserId = lastUpdateUserId;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "last_update_ts", length = 19)
   public Date getLastUpdateTs()
   {
      return this.lastUpdateTs;
   }

   public void setLastUpdateTs(Date lastUpdateTs)
   {
      this.lastUpdateTs = lastUpdateTs;
   }

}
