package org.agilekartV2.model;

// Generated Jul 16, 2015 1:41:40 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Event generated by hbm2java
 */
@Entity
@Table(name = "event"
      , catalog = "agilekartV2")
@XmlRootElement
public class Event implements java.io.Serializable
{

   private String eventId;
   private String eventName;
   private String eventDesc;
   private String lastUpdateUserId;
   private Date lastUpdateTs;

   public Event()
   {
   }

   public Event(String eventId)
   {
      this.eventId = eventId;
   }

   public Event(String eventId, String eventName, String eventDesc, String lastUpdateUserId, Date lastUpdateTs)
   {
      this.eventId = eventId;
      this.eventName = eventName;
      this.eventDesc = eventDesc;
      this.lastUpdateUserId = lastUpdateUserId;
      this.lastUpdateTs = lastUpdateTs;
   }

   @Id
   @Column(name = "event_id", unique = true, nullable = false, length = 45)
   public String getEventId()
   {
      return this.eventId;
   }

   public void setEventId(String eventId)
   {
      this.eventId = eventId;
   }

   @Column(name = "event_name", length = 45)
   public String getEventName()
   {
      return this.eventName;
   }

   public void setEventName(String eventName)
   {
      this.eventName = eventName;
   }

   @Column(name = "event_desc", length = 500)
   public String getEventDesc()
   {
      return this.eventDesc;
   }

   public void setEventDesc(String eventDesc)
   {
      this.eventDesc = eventDesc;
   }

   @Column(name = "last_update_user_id", length = 45)
   public String getLastUpdateUserId()
   {
      return this.lastUpdateUserId;
   }

   public void setLastUpdateUserId(String lastUpdateUserId)
   {
      this.lastUpdateUserId = lastUpdateUserId;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "last_update_ts", length = 19)
   public Date getLastUpdateTs()
   {
      return this.lastUpdateTs;
   }

   public void setLastUpdateTs(Date lastUpdateTs)
   {
      this.lastUpdateTs = lastUpdateTs;
   }

}
