package org.agilekartV2.model;

// Generated Jul 16, 2015 1:41:40 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * LoyaltyProgramTier generated by hbm2java
 */
@Entity
@Table(name = "loyalty_program_tier"
      , catalog = "agilekartV2")
@XmlRootElement
public class LoyaltyProgramTier implements java.io.Serializable
{

   private String tierId;
   private String tierName;
   private Integer tierMinPoints;
   private Integer tierMaxPoints;
   private String lastUpdateUserId;
   private Date lastUpdateTs;

   public LoyaltyProgramTier()
   {
   }

   public LoyaltyProgramTier(String tierId, String tierName)
   {
      this.tierId = tierId;
      this.tierName = tierName;
   }

   public LoyaltyProgramTier(String tierId, String tierName, Integer tierMinPoints, Integer tierMaxPoints, String lastUpdateUserId, Date lastUpdateTs)
   {
      this.tierId = tierId;
      this.tierName = tierName;
      this.tierMinPoints = tierMinPoints;
      this.tierMaxPoints = tierMaxPoints;
      this.lastUpdateUserId = lastUpdateUserId;
      this.lastUpdateTs = lastUpdateTs;
   }

   @Id
   @Column(name = "tier_id", unique = true, nullable = false, length = 45)
   public String getTierId()
   {
      return this.tierId;
   }

   public void setTierId(String tierId)
   {
      this.tierId = tierId;
   }

   @Column(name = "tier_name", nullable = false, length = 45)
   public String getTierName()
   {
      return this.tierName;
   }

   public void setTierName(String tierName)
   {
      this.tierName = tierName;
   }

   @Column(name = "tier_min_points")
   public Integer getTierMinPoints()
   {
      return this.tierMinPoints;
   }

   public void setTierMinPoints(Integer tierMinPoints)
   {
      this.tierMinPoints = tierMinPoints;
   }

   @Column(name = "tier_max_points")
   public Integer getTierMaxPoints()
   {
      return this.tierMaxPoints;
   }

   public void setTierMaxPoints(Integer tierMaxPoints)
   {
      this.tierMaxPoints = tierMaxPoints;
   }

   @Column(name = "last_update_user_id", length = 45)
   public String getLastUpdateUserId()
   {
      return this.lastUpdateUserId;
   }

   public void setLastUpdateUserId(String lastUpdateUserId)
   {
      this.lastUpdateUserId = lastUpdateUserId;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "last_update_ts", length = 19)
   public Date getLastUpdateTs()
   {
      return this.lastUpdateTs;
   }

   public void setLastUpdateTs(Date lastUpdateTs)
   {
      this.lastUpdateTs = lastUpdateTs;
   }

}
