package org.agilekartV2.model;

// Generated Jul 16, 2015 1:41:40 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * LoyaltyEventDetails generated by hbm2java
 */
@Entity
@Table(name = "loyalty_event_details"
      , catalog = "agilekartV2")
@XmlRootElement
public class LoyaltyEventDetails implements java.io.Serializable
{

   private String loyaltyEventDetailsId;
   private String eventId;
   private String tierId;
   private Integer pointsEarned;
   private String lastUpdateUserId;
   private Date lastUpdateTs;

   public LoyaltyEventDetails()
   {
   }

   public LoyaltyEventDetails(String loyaltyEventDetailsId, String eventId, String tierId)
   {
      this.loyaltyEventDetailsId = loyaltyEventDetailsId;
      this.eventId = eventId;
      this.tierId = tierId;
   }

   public LoyaltyEventDetails(String loyaltyEventDetailsId, String eventId, String tierId, Integer pointsEarned, String lastUpdateUserId, Date lastUpdateTs)
   {
      this.loyaltyEventDetailsId = loyaltyEventDetailsId;
      this.eventId = eventId;
      this.tierId = tierId;
      this.pointsEarned = pointsEarned;
      this.lastUpdateUserId = lastUpdateUserId;
      this.lastUpdateTs = lastUpdateTs;
   }

   @Id
   @Column(name = "loyalty_event_details_id", unique = true, nullable = false, length = 45)
   public String getLoyaltyEventDetailsId()
   {
      return this.loyaltyEventDetailsId;
   }

   public void setLoyaltyEventDetailsId(String loyaltyEventDetailsId)
   {
      this.loyaltyEventDetailsId = loyaltyEventDetailsId;
   }

   @Column(name = "event_id", nullable = false, length = 45)
   public String getEventId()
   {
      return this.eventId;
   }

   public void setEventId(String eventId)
   {
      this.eventId = eventId;
   }

   @Column(name = "tier_id", nullable = false, length = 45)
   public String getTierId()
   {
      return this.tierId;
   }

   public void setTierId(String tierId)
   {
      this.tierId = tierId;
   }

   @Column(name = "points_earned")
   public Integer getPointsEarned()
   {
      return this.pointsEarned;
   }

   public void setPointsEarned(Integer pointsEarned)
   {
      this.pointsEarned = pointsEarned;
   }

   @Column(name = "last_update_user_id", length = 45)
   public String getLastUpdateUserId()
   {
      return this.lastUpdateUserId;
   }

   public void setLastUpdateUserId(String lastUpdateUserId)
   {
      this.lastUpdateUserId = lastUpdateUserId;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "last_update_ts", length = 19)
   public Date getLastUpdateTs()
   {
      return this.lastUpdateTs;
   }

   public void setLastUpdateTs(Date lastUpdateTs)
   {
      this.lastUpdateTs = lastUpdateTs;
   }

}
