package org.agilekartV2.model;

// Generated Jul 16, 2015 1:41:40 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * LoyaltyProgramMerchant generated by hbm2java
 */
@Entity
@Table(name = "loyalty_program_merchant"
      , catalog = "agilekartV2")
@XmlRootElement
public class LoyaltyProgramMerchant implements java.io.Serializable
{

   private String loyaltyProgramMerchantId;
   private String merchantId;
   private Date startDate;
   private Date endDate;
   private Character programParticipateFlag;
   private Float amountSpent;
   private Integer pointsEarned;
   private Integer pointsRedeemed;
   private Float amountRedeemed;
   private Float minAmountSpent;
   private String lastUpdateUserId;
   private Date lastUpdateTs;

   public LoyaltyProgramMerchant()
   {
   }

   public LoyaltyProgramMerchant(String loyaltyProgramMerchantId, String merchantId)
   {
      this.loyaltyProgramMerchantId = loyaltyProgramMerchantId;
      this.merchantId = merchantId;
   }

   public LoyaltyProgramMerchant(String loyaltyProgramMerchantId, String merchantId, Date startDate, Date endDate, Character programParticipateFlag, Float amountSpent, Integer pointsEarned, Integer pointsRedeemed, Float amountRedeemed, Float minAmountSpent, String lastUpdateUserId, Date lastUpdateTs)
   {
      this.loyaltyProgramMerchantId = loyaltyProgramMerchantId;
      this.merchantId = merchantId;
      this.startDate = startDate;
      this.endDate = endDate;
      this.programParticipateFlag = programParticipateFlag;
      this.amountSpent = amountSpent;
      this.pointsEarned = pointsEarned;
      this.pointsRedeemed = pointsRedeemed;
      this.amountRedeemed = amountRedeemed;
      this.minAmountSpent = minAmountSpent;
      this.lastUpdateUserId = lastUpdateUserId;
      this.lastUpdateTs = lastUpdateTs;
   }

   @Id
   @Column(name = "loyalty_program_merchant_id", unique = true, nullable = false, length = 45)
   public String getLoyaltyProgramMerchantId()
   {
      return this.loyaltyProgramMerchantId;
   }

   public void setLoyaltyProgramMerchantId(String loyaltyProgramMerchantId)
   {
      this.loyaltyProgramMerchantId = loyaltyProgramMerchantId;
   }

   @Column(name = "merchant_id", nullable = false, length = 45)
   public String getMerchantId()
   {
      return this.merchantId;
   }

   public void setMerchantId(String merchantId)
   {
      this.merchantId = merchantId;
   }

   @Temporal(TemporalType.DATE)
   @Column(name = "start_date", length = 10)
   public Date getStartDate()
   {
      return this.startDate;
   }

   public void setStartDate(Date startDate)
   {
      this.startDate = startDate;
   }

   @Temporal(TemporalType.DATE)
   @Column(name = "end_date", length = 10)
   public Date getEndDate()
   {
      return this.endDate;
   }

   public void setEndDate(Date endDate)
   {
      this.endDate = endDate;
   }

   @Column(name = "program_participate_flag", length = 1)
   public Character getProgramParticipateFlag()
   {
      return this.programParticipateFlag;
   }

   public void setProgramParticipateFlag(Character programParticipateFlag)
   {
      this.programParticipateFlag = programParticipateFlag;
   }

   @Column(name = "amount_spent", precision = 12, scale = 0)
   public Float getAmountSpent()
   {
      return this.amountSpent;
   }

   public void setAmountSpent(Float amountSpent)
   {
      this.amountSpent = amountSpent;
   }

   @Column(name = "points_earned")
   public Integer getPointsEarned()
   {
      return this.pointsEarned;
   }

   public void setPointsEarned(Integer pointsEarned)
   {
      this.pointsEarned = pointsEarned;
   }

   @Column(name = "points_redeemed")
   public Integer getPointsRedeemed()
   {
      return this.pointsRedeemed;
   }

   public void setPointsRedeemed(Integer pointsRedeemed)
   {
      this.pointsRedeemed = pointsRedeemed;
   }

   @Column(name = "amount_redeemed", precision = 12, scale = 0)
   public Float getAmountRedeemed()
   {
      return this.amountRedeemed;
   }

   public void setAmountRedeemed(Float amountRedeemed)
   {
      this.amountRedeemed = amountRedeemed;
   }

   @Column(name = "min_amount_spent", precision = 12, scale = 0)
   public Float getMinAmountSpent()
   {
      return this.minAmountSpent;
   }

   public void setMinAmountSpent(Float minAmountSpent)
   {
      this.minAmountSpent = minAmountSpent;
   }

   @Column(name = "last_update_user_id", length = 45)
   public String getLastUpdateUserId()
   {
      return this.lastUpdateUserId;
   }

   public void setLastUpdateUserId(String lastUpdateUserId)
   {
      this.lastUpdateUserId = lastUpdateUserId;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "last_update_ts", length = 19)
   public Date getLastUpdateTs()
   {
      return this.lastUpdateTs;
   }

   public void setLastUpdateTs(Date lastUpdateTs)
   {
      this.lastUpdateTs = lastUpdateTs;
   }

}
