package org.agilekartV2.model;

// Generated Jul 16, 2015 1:41:40 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * MerchantFeatures generated by hbm2java
 */
@Entity
@Table(name = "merchant_features"
      , catalog = "agilekartV2")
@XmlRootElement
public class MerchantFeatures implements java.io.Serializable
{

   private String merchantFeaturesId;
   private String merchantId;
   private String featureOptionsId;
   private String featureId;
   private String lastUpdateUserId;
   private Date lastUpdateTs;

   public MerchantFeatures()
   {
   }

   public MerchantFeatures(String merchantFeaturesId, String merchantId, String featureOptionsId, String featureId)
   {
      this.merchantFeaturesId = merchantFeaturesId;
      this.merchantId = merchantId;
      this.featureOptionsId = featureOptionsId;
      this.featureId = featureId;
   }

   public MerchantFeatures(String merchantFeaturesId, String merchantId, String featureOptionsId, String featureId, String lastUpdateUserId, Date lastUpdateTs)
   {
      this.merchantFeaturesId = merchantFeaturesId;
      this.merchantId = merchantId;
      this.featureOptionsId = featureOptionsId;
      this.featureId = featureId;
      this.lastUpdateUserId = lastUpdateUserId;
      this.lastUpdateTs = lastUpdateTs;
   }

   @Id
   @Column(name = "merchant_features_id", unique = true, nullable = false, length = 45)
   public String getMerchantFeaturesId()
   {
      return this.merchantFeaturesId;
   }

   public void setMerchantFeaturesId(String merchantFeaturesId)
   {
      this.merchantFeaturesId = merchantFeaturesId;
   }

   @Column(name = "merchant_id", nullable = false, length = 45)
   public String getMerchantId()
   {
      return this.merchantId;
   }

   public void setMerchantId(String merchantId)
   {
      this.merchantId = merchantId;
   }

   @Column(name = "feature_options_id", nullable = false, length = 45)
   public String getFeatureOptionsId()
   {
      return this.featureOptionsId;
   }

   public void setFeatureOptionsId(String featureOptionsId)
   {
      this.featureOptionsId = featureOptionsId;
   }

   @Column(name = "feature_id", nullable = false, length = 45)
   public String getFeatureId()
   {
      return this.featureId;
   }

   public void setFeatureId(String featureId)
   {
      this.featureId = featureId;
   }

   @Column(name = "last_update_user_id", length = 45)
   public String getLastUpdateUserId()
   {
      return this.lastUpdateUserId;
   }

   public void setLastUpdateUserId(String lastUpdateUserId)
   {
      this.lastUpdateUserId = lastUpdateUserId;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "last_update_ts", length = 19)
   public Date getLastUpdateTs()
   {
      return this.lastUpdateTs;
   }

   public void setLastUpdateTs(Date lastUpdateTs)
   {
      this.lastUpdateTs = lastUpdateTs;
   }

}
