package org.agilekartV2.model;

// Generated Jul 16, 2015 1:41:40 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * MerchantCategory generated by hbm2java
 */
@Entity
@Table(name = "merchant_category"
      , catalog = "agilekartV2")
@XmlRootElement
public class MerchantCategory implements java.io.Serializable
{

   private String merchantCategoryId;
   private String categoryId;
   private String merchantId;
   private String lastUpdateUserId;
   private Date lastUpdateTs;

   public MerchantCategory()
   {
   }

   public MerchantCategory(String merchantCategoryId, String categoryId, String merchantId)
   {
      this.merchantCategoryId = merchantCategoryId;
      this.categoryId = categoryId;
      this.merchantId = merchantId;
   }

   public MerchantCategory(String merchantCategoryId, String categoryId, String merchantId, String lastUpdateUserId, Date lastUpdateTs)
   {
      this.merchantCategoryId = merchantCategoryId;
      this.categoryId = categoryId;
      this.merchantId = merchantId;
      this.lastUpdateUserId = lastUpdateUserId;
      this.lastUpdateTs = lastUpdateTs;
   }

   @Id
   @Column(name = "merchant_category_id", unique = true, nullable = false, length = 45)
   public String getMerchantCategoryId()
   {
      return this.merchantCategoryId;
   }

   public void setMerchantCategoryId(String merchantCategoryId)
   {
      this.merchantCategoryId = merchantCategoryId;
   }

   @Column(name = "category_id", nullable = false, length = 45)
   public String getCategoryId()
   {
      return this.categoryId;
   }

   public void setCategoryId(String categoryId)
   {
      this.categoryId = categoryId;
   }

   @Column(name = "merchant_id", nullable = false, length = 45)
   public String getMerchantId()
   {
      return this.merchantId;
   }

   public void setMerchantId(String merchantId)
   {
      this.merchantId = merchantId;
   }

   @Column(name = "last_update_user_id", length = 45)
   public String getLastUpdateUserId()
   {
      return this.lastUpdateUserId;
   }

   public void setLastUpdateUserId(String lastUpdateUserId)
   {
      this.lastUpdateUserId = lastUpdateUserId;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "last_update_ts", length = 19)
   public Date getLastUpdateTs()
   {
      return this.lastUpdateTs;
   }

   public void setLastUpdateTs(Date lastUpdateTs)
   {
      this.lastUpdateTs = lastUpdateTs;
   }

}
