package org.agilekartV2.model;

// Generated Jul 16, 2015 1:41:40 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Merchant generated by hbm2java
 */
@Entity
@Table(name = "merchant"
      , catalog = "agilekartV2"
      , uniqueConstraints = @UniqueConstraint(columnNames = "merchant_name"))
@XmlRootElement
public class Merchant implements java.io.Serializable
{

   private String merchantId;
   private String merchantName;
   private String merchantEmail;
   private String merchantPassword;
   private String merchantPhoneNo;
   private Boolean merchantEmailVerified;
   private String merchantVerificationCode;
   private Integer minOrder;
   private Integer deliveryTime;
   private Integer merchantRating;
   private String lastUpdateUserId;
   private Date lastUpdateTs;

   public Merchant()
   {
   }

   public Merchant(String merchantId, String merchantName, String merchantEmail, String merchantPassword)
   {
      this.merchantId = merchantId;
      this.merchantName = merchantName;
      this.merchantEmail = merchantEmail;
      this.merchantPassword = merchantPassword;
   }

   public Merchant(String merchantId, String merchantName, String merchantEmail, String merchantPassword, String merchantPhoneNo, Boolean merchantEmailVerified, String merchantVerificationCode, Integer minOrder, Integer deliveryTime, Integer merchantRating, String lastUpdateUserId, Date lastUpdateTs)
   {
      this.merchantId = merchantId;
      this.merchantName = merchantName;
      this.merchantEmail = merchantEmail;
      this.merchantPassword = merchantPassword;
      this.merchantPhoneNo = merchantPhoneNo;
      this.merchantEmailVerified = merchantEmailVerified;
      this.merchantVerificationCode = merchantVerificationCode;
      this.minOrder = minOrder;
      this.deliveryTime = deliveryTime;
      this.merchantRating = merchantRating;
      this.lastUpdateUserId = lastUpdateUserId;
      this.lastUpdateTs = lastUpdateTs;
   }

   @Id
   @Column(name = "merchant_id", unique = true, nullable = false, length = 45)
   public String getMerchantId()
   {
      return this.merchantId;
   }

   public void setMerchantId(String merchantId)
   {
      this.merchantId = merchantId;
   }

   @Column(name = "merchant_name", unique = true, nullable = false, length = 50)
   public String getMerchantName()
   {
      return this.merchantName;
   }

   public void setMerchantName(String merchantName)
   {
      this.merchantName = merchantName;
   }

   @Column(name = "merchant_email", nullable = false, length = 500)
   public String getMerchantEmail()
   {
      return this.merchantEmail;
   }

   public void setMerchantEmail(String merchantEmail)
   {
      this.merchantEmail = merchantEmail;
   }

   @Column(name = "merchant_password", nullable = false, length = 45)
   public String getMerchantPassword()
   {
      return this.merchantPassword;
   }

   public void setMerchantPassword(String merchantPassword)
   {
      this.merchantPassword = merchantPassword;
   }

   @Column(name = "merchant_phone_no", length = 15)
   public String getMerchantPhoneNo()
   {
      return this.merchantPhoneNo;
   }

   public void setMerchantPhoneNo(String merchantPhoneNo)
   {
      this.merchantPhoneNo = merchantPhoneNo;
   }

   @Column(name = "merchant_email_verified")
   public Boolean getMerchantEmailVerified()
   {
      return this.merchantEmailVerified;
   }

   public void setMerchantEmailVerified(Boolean merchantEmailVerified)
   {
      this.merchantEmailVerified = merchantEmailVerified;
   }

   @Column(name = "merchant_verification_code", length = 20)
   public String getMerchantVerificationCode()
   {
      return this.merchantVerificationCode;
   }

   public void setMerchantVerificationCode(String merchantVerificationCode)
   {
      this.merchantVerificationCode = merchantVerificationCode;
   }

   @Column(name = "min_order")
   public Integer getMinOrder()
   {
      return this.minOrder;
   }

   public void setMinOrder(Integer minOrder)
   {
      this.minOrder = minOrder;
   }

   @Column(name = "delivery_time")
   public Integer getDeliveryTime()
   {
      return this.deliveryTime;
   }

   public void setDeliveryTime(Integer deliveryTime)
   {
      this.deliveryTime = deliveryTime;
   }

   @Column(name = "merchant_rating")
   public Integer getMerchantRating()
   {
      return this.merchantRating;
   }

   public void setMerchantRating(Integer merchantRating)
   {
      this.merchantRating = merchantRating;
   }

   @Column(name = "last_update_user_id", length = 45)
   public String getLastUpdateUserId()
   {
      return this.lastUpdateUserId;
   }

   public void setLastUpdateUserId(String lastUpdateUserId)
   {
      this.lastUpdateUserId = lastUpdateUserId;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "last_update_ts", length = 19)
   public Date getLastUpdateTs()
   {
      return this.lastUpdateTs;
   }

   public void setLastUpdateTs(Date lastUpdateTs)
   {
      this.lastUpdateTs = lastUpdateTs;
   }

}
