package org.agilekartV2.model;

// Generated Jul 16, 2015 1:41:40 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * MerchantReview generated by hbm2java
 */
@Entity
@Table(name = "merchant_review"
      , catalog = "agilekartV2")
@XmlRootElement
public class MerchantReview implements java.io.Serializable
{

   private String merchantReviewId;
   private String merchantReview;
   private String merchantId;
   private String userId;
   private Integer merchantRating;
   private String lastUpdateUserId;
   private Date lastUpdateTs;

   public MerchantReview()
   {
   }

   public MerchantReview(String merchantReviewId, String merchantReview, String merchantId, String userId)
   {
      this.merchantReviewId = merchantReviewId;
      this.merchantReview = merchantReview;
      this.merchantId = merchantId;
      this.userId = userId;
   }

   public MerchantReview(String merchantReviewId, String merchantReview, String merchantId, String userId, Integer merchantRating, String lastUpdateUserId, Date lastUpdateTs)
   {
      this.merchantReviewId = merchantReviewId;
      this.merchantReview = merchantReview;
      this.merchantId = merchantId;
      this.userId = userId;
      this.merchantRating = merchantRating;
      this.lastUpdateUserId = lastUpdateUserId;
      this.lastUpdateTs = lastUpdateTs;
   }

   @Id
   @Column(name = "merchant_review_id", unique = true, nullable = false, length = 45)
   public String getMerchantReviewId()
   {
      return this.merchantReviewId;
   }

   public void setMerchantReviewId(String merchantReviewId)
   {
      this.merchantReviewId = merchantReviewId;
   }

   @Column(name = "merchant_review", nullable = false, length = 150)
   public String getMerchantReview()
   {
      return this.merchantReview;
   }

   public void setMerchantReview(String merchantReview)
   {
      this.merchantReview = merchantReview;
   }

   @Column(name = "merchant_id", nullable = false, length = 45)
   public String getMerchantId()
   {
      return this.merchantId;
   }

   public void setMerchantId(String merchantId)
   {
      this.merchantId = merchantId;
   }

   @Column(name = "user_id", nullable = false, length = 45)
   public String getUserId()
   {
      return this.userId;
   }

   public void setUserId(String userId)
   {
      this.userId = userId;
   }

   @Column(name = "merchant_rating")
   public Integer getMerchantRating()
   {
      return this.merchantRating;
   }

   public void setMerchantRating(Integer merchantRating)
   {
      this.merchantRating = merchantRating;
   }

   @Column(name = "last_update_user_id", length = 45)
   public String getLastUpdateUserId()
   {
      return this.lastUpdateUserId;
   }

   public void setLastUpdateUserId(String lastUpdateUserId)
   {
      this.lastUpdateUserId = lastUpdateUserId;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "last_update_ts", length = 19)
   public Date getLastUpdateTs()
   {
      return this.lastUpdateTs;
   }

   public void setLastUpdateTs(Date lastUpdateTs)
   {
      this.lastUpdateTs = lastUpdateTs;
   }

}
