package org.agilekartV2.model;

// Generated Jul 16, 2015 1:41:40 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * MerchantPaymentGateway generated by hbm2java
 */
@Entity
@Table(name = "merchant_payment_gateway"
      , catalog = "agilekartV2")
@XmlRootElement
public class MerchantPaymentGateway implements java.io.Serializable
{

   private String merchantPaymentGatewayId;
   private String paymentGatewayId;
   private String merchantId;
   private String lastUpdateUserId;
   private Date lastUpdateTs;

   public MerchantPaymentGateway()
   {
   }

   public MerchantPaymentGateway(String merchantPaymentGatewayId, String paymentGatewayId, String merchantId)
   {
      this.merchantPaymentGatewayId = merchantPaymentGatewayId;
      this.paymentGatewayId = paymentGatewayId;
      this.merchantId = merchantId;
   }

   public MerchantPaymentGateway(String merchantPaymentGatewayId, String paymentGatewayId, String merchantId, String lastUpdateUserId, Date lastUpdateTs)
   {
      this.merchantPaymentGatewayId = merchantPaymentGatewayId;
      this.paymentGatewayId = paymentGatewayId;
      this.merchantId = merchantId;
      this.lastUpdateUserId = lastUpdateUserId;
      this.lastUpdateTs = lastUpdateTs;
   }

   @Id
   @Column(name = "merchant_payment_gateway_id", unique = true, nullable = false, length = 45)
   public String getMerchantPaymentGatewayId()
   {
      return this.merchantPaymentGatewayId;
   }

   public void setMerchantPaymentGatewayId(String merchantPaymentGatewayId)
   {
      this.merchantPaymentGatewayId = merchantPaymentGatewayId;
   }

   @Column(name = "payment_gateway_id", nullable = false, length = 45)
   public String getPaymentGatewayId()
   {
      return this.paymentGatewayId;
   }

   public void setPaymentGatewayId(String paymentGatewayId)
   {
      this.paymentGatewayId = paymentGatewayId;
   }

   @Column(name = "merchant_id", nullable = false, length = 45)
   public String getMerchantId()
   {
      return this.merchantId;
   }

   public void setMerchantId(String merchantId)
   {
      this.merchantId = merchantId;
   }

   @Column(name = "last_update_user_id", length = 45)
   public String getLastUpdateUserId()
   {
      return this.lastUpdateUserId;
   }

   public void setLastUpdateUserId(String lastUpdateUserId)
   {
      this.lastUpdateUserId = lastUpdateUserId;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "last_update_ts", length = 19)
   public Date getLastUpdateTs()
   {
      return this.lastUpdateTs;
   }

   public void setLastUpdateTs(Date lastUpdateTs)
   {
      this.lastUpdateTs = lastUpdateTs;
   }

}
