package org.agilekartV2.model;

// Generated Jul 16, 2015 1:41:40 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Options generated by hbm2java
 */
@Entity
@Table(name = "options"
      , catalog = "agilekartV2"
      , uniqueConstraints = @UniqueConstraint(columnNames = { "option_name", "option_group_id" }))
@XmlRootElement
public class Options implements java.io.Serializable
{

   private String optionId;
   private String optionGroupId;
   private String optionName;
   private String lastUpdateUserId;
   private Date lastUpdateTs;

   public Options()
   {
   }

   public Options(String optionId, String optionGroupId, String optionName)
   {
      this.optionId = optionId;
      this.optionGroupId = optionGroupId;
      this.optionName = optionName;
   }

   public Options(String optionId, String optionGroupId, String optionName, String lastUpdateUserId, Date lastUpdateTs)
   {
      this.optionId = optionId;
      this.optionGroupId = optionGroupId;
      this.optionName = optionName;
      this.lastUpdateUserId = lastUpdateUserId;
      this.lastUpdateTs = lastUpdateTs;
   }

   @Id
   @Column(name = "option_id", unique = true, nullable = false, length = 45)
   public String getOptionId()
   {
      return this.optionId;
   }

   public void setOptionId(String optionId)
   {
      this.optionId = optionId;
   }

   @Column(name = "option_group_id", nullable = false, length = 45)
   public String getOptionGroupId()
   {
      return this.optionGroupId;
   }

   public void setOptionGroupId(String optionGroupId)
   {
      this.optionGroupId = optionGroupId;
   }

   @Column(name = "option_name", nullable = false, length = 50)
   public String getOptionName()
   {
      return this.optionName;
   }

   public void setOptionName(String optionName)
   {
      this.optionName = optionName;
   }

   @Column(name = "last_update_user_id", length = 45)
   public String getLastUpdateUserId()
   {
      return this.lastUpdateUserId;
   }

   public void setLastUpdateUserId(String lastUpdateUserId)
   {
      this.lastUpdateUserId = lastUpdateUserId;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "last_update_ts", length = 19)
   public Date getLastUpdateTs()
   {
      return this.lastUpdateTs;
   }

   public void setLastUpdateTs(Date lastUpdateTs)
   {
      this.lastUpdateTs = lastUpdateTs;
   }

}
