package org.agilekartV2.model;

// Generated Jul 16, 2015 1:41:40 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * OrderDetails generated by hbm2java
 */
@Entity
@Table(name = "order_details"
      , catalog = "agilekartV2")
@XmlRootElement
public class OrderDetails implements java.io.Serializable
{

   private String detailId;
   private String orderId;
   private String productId;
   private String detailName;
   private float detailPrice;
   private int detailQuantity;
   private String lastUpdateUserId;
   private Date lastUpdateTs;

   public OrderDetails()
   {
   }

   public OrderDetails(String detailId, String orderId, String productId, String detailName, float detailPrice, int detailQuantity)
   {
      this.detailId = detailId;
      this.orderId = orderId;
      this.productId = productId;
      this.detailName = detailName;
      this.detailPrice = detailPrice;
      this.detailQuantity = detailQuantity;
   }

   public OrderDetails(String detailId, String orderId, String productId, String detailName, float detailPrice, int detailQuantity, String lastUpdateUserId, Date lastUpdateTs)
   {
      this.detailId = detailId;
      this.orderId = orderId;
      this.productId = productId;
      this.detailName = detailName;
      this.detailPrice = detailPrice;
      this.detailQuantity = detailQuantity;
      this.lastUpdateUserId = lastUpdateUserId;
      this.lastUpdateTs = lastUpdateTs;
   }

   @Id
   @Column(name = "detail_id", unique = true, nullable = false, length = 45)
   public String getDetailId()
   {
      return this.detailId;
   }

   public void setDetailId(String detailId)
   {
      this.detailId = detailId;
   }

   @Column(name = "order_id", nullable = false, length = 45)
   public String getOrderId()
   {
      return this.orderId;
   }

   public void setOrderId(String orderId)
   {
      this.orderId = orderId;
   }

   @Column(name = "product_id", nullable = false, length = 45)
   public String getProductId()
   {
      return this.productId;
   }

   public void setProductId(String productId)
   {
      this.productId = productId;
   }

   @Column(name = "detail_name", nullable = false, length = 250)
   public String getDetailName()
   {
      return this.detailName;
   }

   public void setDetailName(String detailName)
   {
      this.detailName = detailName;
   }

   @Column(name = "detail_price", nullable = false, precision = 12, scale = 0)
   public float getDetailPrice()
   {
      return this.detailPrice;
   }

   public void setDetailPrice(float detailPrice)
   {
      this.detailPrice = detailPrice;
   }

   @Column(name = "detail_quantity", nullable = false)
   public int getDetailQuantity()
   {
      return this.detailQuantity;
   }

   public void setDetailQuantity(int detailQuantity)
   {
      this.detailQuantity = detailQuantity;
   }

   @Column(name = "last_update_user_id", length = 45)
   public String getLastUpdateUserId()
   {
      return this.lastUpdateUserId;
   }

   public void setLastUpdateUserId(String lastUpdateUserId)
   {
      this.lastUpdateUserId = lastUpdateUserId;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "last_update_ts", length = 19)
   public Date getLastUpdateTs()
   {
      return this.lastUpdateTs;
   }

   public void setLastUpdateTs(Date lastUpdateTs)
   {
      this.lastUpdateTs = lastUpdateTs;
   }

}
