package org.agilekartV2.model;

// Generated Jul 16, 2015 1:41:40 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * OrderStatus generated by hbm2java
 */
@Entity
@Table(name = "order_status"
      , catalog = "agilekartV2")
@XmlRootElement
public class OrderStatus implements java.io.Serializable
{

   private String orderStatusId;
   private String orderId;
   private String orderStatusDescId;
   private String orderStatusComment;
   private Character orderStatusIsActive;
   private String lastUpdateUserId;
   private Date lastUpdateTs;

   public OrderStatus()
   {
   }

   public OrderStatus(String orderStatusId, String orderId, String orderStatusDescId)
   {
      this.orderStatusId = orderStatusId;
      this.orderId = orderId;
      this.orderStatusDescId = orderStatusDescId;
   }

   public OrderStatus(String orderStatusId, String orderId, String orderStatusDescId, String orderStatusComment, Character orderStatusIsActive, String lastUpdateUserId, Date lastUpdateTs)
   {
      this.orderStatusId = orderStatusId;
      this.orderId = orderId;
      this.orderStatusDescId = orderStatusDescId;
      this.orderStatusComment = orderStatusComment;
      this.orderStatusIsActive = orderStatusIsActive;
      this.lastUpdateUserId = lastUpdateUserId;
      this.lastUpdateTs = lastUpdateTs;
   }

   @Id
   @Column(name = "order_status_id", unique = true, nullable = false, length = 45)
   public String getOrderStatusId()
   {
      return this.orderStatusId;
   }

   public void setOrderStatusId(String orderStatusId)
   {
      this.orderStatusId = orderStatusId;
   }

   @Column(name = "order_id", nullable = false, length = 45)
   public String getOrderId()
   {
      return this.orderId;
   }

   public void setOrderId(String orderId)
   {
      this.orderId = orderId;
   }

   @Column(name = "order_status_desc_id", nullable = false, length = 45)
   public String getOrderStatusDescId()
   {
      return this.orderStatusDescId;
   }

   public void setOrderStatusDescId(String orderStatusDescId)
   {
      this.orderStatusDescId = orderStatusDescId;
   }

   @Column(name = "order_status_comment", length = 500)
   public String getOrderStatusComment()
   {
      return this.orderStatusComment;
   }

   public void setOrderStatusComment(String orderStatusComment)
   {
      this.orderStatusComment = orderStatusComment;
   }

   @Column(name = "order_status_is_active", length = 1)
   public Character getOrderStatusIsActive()
   {
      return this.orderStatusIsActive;
   }

   public void setOrderStatusIsActive(Character orderStatusIsActive)
   {
      this.orderStatusIsActive = orderStatusIsActive;
   }

   @Column(name = "last_update_user_id", length = 45)
   public String getLastUpdateUserId()
   {
      return this.lastUpdateUserId;
   }

   public void setLastUpdateUserId(String lastUpdateUserId)
   {
      this.lastUpdateUserId = lastUpdateUserId;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "last_update_ts", length = 19)
   public Date getLastUpdateTs()
   {
      return this.lastUpdateTs;
   }

   public void setLastUpdateTs(Date lastUpdateTs)
   {
      this.lastUpdateTs = lastUpdateTs;
   }

}
