package org.agilekartV2.model;

// Generated Jul 16, 2015 1:41:40 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * OrderStatusDesc generated by hbm2java
 */
@Entity
@Table(name = "order_status_desc"
      , catalog = "agilekartV2")
@XmlRootElement
public class OrderStatusDesc implements java.io.Serializable
{

   private String orderStatusDescId;
   private String orderStatusDescText;
   private String lastUpdateUserId;
   private Date lastUpdateTs;

   public OrderStatusDesc()
   {
   }

   public OrderStatusDesc(String orderStatusDescId)
   {
      this.orderStatusDescId = orderStatusDescId;
   }

   public OrderStatusDesc(String orderStatusDescId, String orderStatusDescText, String lastUpdateUserId, Date lastUpdateTs)
   {
      this.orderStatusDescId = orderStatusDescId;
      this.orderStatusDescText = orderStatusDescText;
      this.lastUpdateUserId = lastUpdateUserId;
      this.lastUpdateTs = lastUpdateTs;
   }

   @Id
   @Column(name = "order_status_desc_id", unique = true, nullable = false, length = 45)
   public String getOrderStatusDescId()
   {
      return this.orderStatusDescId;
   }

   public void setOrderStatusDescId(String orderStatusDescId)
   {
      this.orderStatusDescId = orderStatusDescId;
   }

   @Column(name = "order_status_desc_text", length = 500)
   public String getOrderStatusDescText()
   {
      return this.orderStatusDescText;
   }

   public void setOrderStatusDescText(String orderStatusDescText)
   {
      this.orderStatusDescText = orderStatusDescText;
   }

   @Column(name = "last_update_user_id", length = 45)
   public String getLastUpdateUserId()
   {
      return this.lastUpdateUserId;
   }

   public void setLastUpdateUserId(String lastUpdateUserId)
   {
      this.lastUpdateUserId = lastUpdateUserId;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "last_update_ts", length = 19)
   public Date getLastUpdateTs()
   {
      return this.lastUpdateTs;
   }

   public void setLastUpdateTs(Date lastUpdateTs)
   {
      this.lastUpdateTs = lastUpdateTs;
   }

}
