package org.agilekartV2.model;

// Generated Jul 16, 2015 1:41:40 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * PaymentGateway generated by hbm2java
 */
@Entity
@Table(name = "payment_gateway"
      , catalog = "agilekartV2")
@XmlRootElement
public class PaymentGateway implements java.io.Serializable
{

   private String paymentGatewayId;
   private String paymentGatewayName;
   private String paymentGatewayDesc;
   private String lastUpdateUserId;
   private Date lastUpdateTs;

   public PaymentGateway()
   {
   }

   public PaymentGateway(String paymentGatewayId)
   {
      this.paymentGatewayId = paymentGatewayId;
   }

   public PaymentGateway(String paymentGatewayId, String paymentGatewayName, String paymentGatewayDesc, String lastUpdateUserId, Date lastUpdateTs)
   {
      this.paymentGatewayId = paymentGatewayId;
      this.paymentGatewayName = paymentGatewayName;
      this.paymentGatewayDesc = paymentGatewayDesc;
      this.lastUpdateUserId = lastUpdateUserId;
      this.lastUpdateTs = lastUpdateTs;
   }

   @Id
   @Column(name = "payment_gateway_id", unique = true, nullable = false, length = 45)
   public String getPaymentGatewayId()
   {
      return this.paymentGatewayId;
   }

   public void setPaymentGatewayId(String paymentGatewayId)
   {
      this.paymentGatewayId = paymentGatewayId;
   }

   @Column(name = "payment_gateway_name", length = 45)
   public String getPaymentGatewayName()
   {
      return this.paymentGatewayName;
   }

   public void setPaymentGatewayName(String paymentGatewayName)
   {
      this.paymentGatewayName = paymentGatewayName;
   }

   @Column(name = "payment_gateway_desc", length = 500)
   public String getPaymentGatewayDesc()
   {
      return this.paymentGatewayDesc;
   }

   public void setPaymentGatewayDesc(String paymentGatewayDesc)
   {
      this.paymentGatewayDesc = paymentGatewayDesc;
   }

   @Column(name = "last_update_user_id", length = 45)
   public String getLastUpdateUserId()
   {
      return this.lastUpdateUserId;
   }

   public void setLastUpdateUserId(String lastUpdateUserId)
   {
      this.lastUpdateUserId = lastUpdateUserId;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "last_update_ts", length = 19)
   public Date getLastUpdateTs()
   {
      return this.lastUpdateTs;
   }

   public void setLastUpdateTs(Date lastUpdateTs)
   {
      this.lastUpdateTs = lastUpdateTs;
   }

}
