package org.agilekartV2.model;

// Generated Jul 16, 2015 1:41:40 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * ProductOption generated by hbm2java
 */
@Entity
@Table(name = "product_option"
      , catalog = "agilekartV2")
@XmlRootElement
public class ProductOption implements java.io.Serializable
{

   private String productOptionId;
   private String productId;
   private String optionGroupId;
   private String optionId;
   private String lastUpdateUserId;
   private Date lastUpdateTs;

   public ProductOption()
   {
   }

   public ProductOption(String productOptionId, String productId, String optionGroupId, String optionId)
   {
      this.productOptionId = productOptionId;
      this.productId = productId;
      this.optionGroupId = optionGroupId;
      this.optionId = optionId;
   }

   public ProductOption(String productOptionId, String productId, String optionGroupId, String optionId, String lastUpdateUserId, Date lastUpdateTs)
   {
      this.productOptionId = productOptionId;
      this.productId = productId;
      this.optionGroupId = optionGroupId;
      this.optionId = optionId;
      this.lastUpdateUserId = lastUpdateUserId;
      this.lastUpdateTs = lastUpdateTs;
   }

   @Id
   @Column(name = "product_option_id", unique = true, nullable = false, length = 45)
   public String getProductOptionId()
   {
      return this.productOptionId;
   }

   public void setProductOptionId(String productOptionId)
   {
      this.productOptionId = productOptionId;
   }

   @Column(name = "product_id", nullable = false, length = 45)
   public String getProductId()
   {
      return this.productId;
   }

   public void setProductId(String productId)
   {
      this.productId = productId;
   }

   @Column(name = "option_group_id", nullable = false, length = 45)
   public String getOptionGroupId()
   {
      return this.optionGroupId;
   }

   public void setOptionGroupId(String optionGroupId)
   {
      this.optionGroupId = optionGroupId;
   }

   @Column(name = "option_id", nullable = false, length = 45)
   public String getOptionId()
   {
      return this.optionId;
   }

   public void setOptionId(String optionId)
   {
      this.optionId = optionId;
   }

   @Column(name = "last_update_user_id", length = 45)
   public String getLastUpdateUserId()
   {
      return this.lastUpdateUserId;
   }

   public void setLastUpdateUserId(String lastUpdateUserId)
   {
      this.lastUpdateUserId = lastUpdateUserId;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "last_update_ts", length = 19)
   public Date getLastUpdateTs()
   {
      return this.lastUpdateTs;
   }

   public void setLastUpdateTs(Date lastUpdateTs)
   {
      this.lastUpdateTs = lastUpdateTs;
   }

}
