package org.agilekartV2.model;

// Generated Jul 16, 2015 1:41:40 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * ProductCategory generated by hbm2java
 */
@Entity
@Table(name = "product_category"
      , catalog = "agilekartV2")
@XmlRootElement
public class ProductCategory implements java.io.Serializable
{

   private String productCategoryId;
   private String productId;
   private String categoryId;
   private String lastUpdateUserId;
   private Date lastUpdateTs;

   public ProductCategory()
   {
   }

   public ProductCategory(String productCategoryId, String productId, String categoryId)
   {
      this.productCategoryId = productCategoryId;
      this.productId = productId;
      this.categoryId = categoryId;
   }

   public ProductCategory(String productCategoryId, String productId, String categoryId, String lastUpdateUserId, Date lastUpdateTs)
   {
      this.productCategoryId = productCategoryId;
      this.productId = productId;
      this.categoryId = categoryId;
      this.lastUpdateUserId = lastUpdateUserId;
      this.lastUpdateTs = lastUpdateTs;
   }

   @Id
   @Column(name = "product_category_id", unique = true, nullable = false, length = 45)
   public String getProductCategoryId()
   {
      return this.productCategoryId;
   }

   public void setProductCategoryId(String productCategoryId)
   {
      this.productCategoryId = productCategoryId;
   }

   @Column(name = "product_id", nullable = false, length = 45)
   public String getProductId()
   {
      return this.productId;
   }

   public void setProductId(String productId)
   {
      this.productId = productId;
   }

   @Column(name = "category_id", nullable = false, length = 45)
   public String getCategoryId()
   {
      return this.categoryId;
   }

   public void setCategoryId(String categoryId)
   {
      this.categoryId = categoryId;
   }

   @Column(name = "last_update_user_id", length = 45)
   public String getLastUpdateUserId()
   {
      return this.lastUpdateUserId;
   }

   public void setLastUpdateUserId(String lastUpdateUserId)
   {
      this.lastUpdateUserId = lastUpdateUserId;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "last_update_ts", length = 19)
   public Date getLastUpdateTs()
   {
      return this.lastUpdateTs;
   }

   public void setLastUpdateTs(Date lastUpdateTs)
   {
      this.lastUpdateTs = lastUpdateTs;
   }

}
