package org.agilekartV2.model;

// Generated Jul 16, 2015 1:41:40 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product"
      , catalog = "agilekartV2")
@XmlRootElement
public class Product implements java.io.Serializable
{

   private String productId;
   private String productName;
   private float productPrice;
   private float productWeight;
   private String productCartDesc;
   private String productShortDesc;
   private String productLongDesc;
   private String productThumb;
   private String productImage;
   private String merchantId;
   private Float productStock;
   private Float productDiscountPercentage;
   private Boolean productUnlimited;
   private Integer productHitCount;
   private Integer productSoldCount;
   private String lastUpdateUserId;
   private Date lastUpdateTs;

   public Product()
   {
   }

   public Product(String productId, String productName, float productPrice, float productWeight, String productCartDesc, String productShortDesc, String productLongDesc, String productThumb, String productImage, String merchantId)
   {
      this.productId = productId;
      this.productName = productName;
      this.productPrice = productPrice;
      this.productWeight = productWeight;
      this.productCartDesc = productCartDesc;
      this.productShortDesc = productShortDesc;
      this.productLongDesc = productLongDesc;
      this.productThumb = productThumb;
      this.productImage = productImage;
      this.merchantId = merchantId;
   }

   public Product(String productId, String productName, float productPrice, float productWeight, String productCartDesc, String productShortDesc, String productLongDesc, String productThumb, String productImage, String merchantId, Float productStock, Float productDiscountPercentage, Boolean productUnlimited, Integer productHitCount, Integer productSoldCount, String lastUpdateUserId, Date lastUpdateTs)
   {
      this.productId = productId;
      this.productName = productName;
      this.productPrice = productPrice;
      this.productWeight = productWeight;
      this.productCartDesc = productCartDesc;
      this.productShortDesc = productShortDesc;
      this.productLongDesc = productLongDesc;
      this.productThumb = productThumb;
      this.productImage = productImage;
      this.merchantId = merchantId;
      this.productStock = productStock;
      this.productDiscountPercentage = productDiscountPercentage;
      this.productUnlimited = productUnlimited;
      this.productHitCount = productHitCount;
      this.productSoldCount = productSoldCount;
      this.lastUpdateUserId = lastUpdateUserId;
      this.lastUpdateTs = lastUpdateTs;
   }

   @Id
   @Column(name = "product_id", unique = true, nullable = false, length = 45)
   public String getProductId()
   {
      return this.productId;
   }

   public void setProductId(String productId)
   {
      this.productId = productId;
   }

   @Column(name = "product_name", nullable = false, length = 100)
   public String getProductName()
   {
      return this.productName;
   }

   public void setProductName(String productName)
   {
      this.productName = productName;
   }

   @Column(name = "product_price", nullable = false, precision = 12, scale = 0)
   public float getProductPrice()
   {
      return this.productPrice;
   }

   public void setProductPrice(float productPrice)
   {
      this.productPrice = productPrice;
   }

   @Column(name = "product_weight", nullable = false, precision = 12, scale = 0)
   public float getProductWeight()
   {
      return this.productWeight;
   }

   public void setProductWeight(float productWeight)
   {
      this.productWeight = productWeight;
   }

   @Column(name = "product_cart_desc", nullable = false, length = 250)
   public String getProductCartDesc()
   {
      return this.productCartDesc;
   }

   public void setProductCartDesc(String productCartDesc)
   {
      this.productCartDesc = productCartDesc;
   }

   @Column(name = "product_short_desc", nullable = false, length = 1000)
   public String getProductShortDesc()
   {
      return this.productShortDesc;
   }

   public void setProductShortDesc(String productShortDesc)
   {
      this.productShortDesc = productShortDesc;
   }

   @Column(name = "product_long_desc", nullable = false, length = 4000)
   public String getProductLongDesc()
   {
      return this.productLongDesc;
   }

   public void setProductLongDesc(String productLongDesc)
   {
      this.productLongDesc = productLongDesc;
   }

   @Column(name = "product_thumb", nullable = false, length = 100)
   public String getProductThumb()
   {
      return this.productThumb;
   }

   public void setProductThumb(String productThumb)
   {
      this.productThumb = productThumb;
   }

   @Column(name = "product_image", nullable = false, length = 100)
   public String getProductImage()
   {
      return this.productImage;
   }

   public void setProductImage(String productImage)
   {
      this.productImage = productImage;
   }

   @Column(name = "merchant_id", nullable = false, length = 45)
   public String getMerchantId()
   {
      return this.merchantId;
   }

   public void setMerchantId(String merchantId)
   {
      this.merchantId = merchantId;
   }

   @Column(name = "product_ stock", precision = 12, scale = 0)
   public Float getProductStock()
   {
      return this.productStock;
   }

   public void setProductStock(Float productStock)
   {
      this.productStock = productStock;
   }

   @Column(name = "product_discount_percentage", precision = 12, scale = 0)
   public Float getProductDiscountPercentage()
   {
      return this.productDiscountPercentage;
   }

   public void setProductDiscountPercentage(Float productDiscountPercentage)
   {
      this.productDiscountPercentage = productDiscountPercentage;
   }

   @Column(name = "product_unlimited")
   public Boolean getProductUnlimited()
   {
      return this.productUnlimited;
   }

   public void setProductUnlimited(Boolean productUnlimited)
   {
      this.productUnlimited = productUnlimited;
   }

   @Column(name = "product_hit_count")
   public Integer getProductHitCount()
   {
      return this.productHitCount;
   }

   public void setProductHitCount(Integer productHitCount)
   {
      this.productHitCount = productHitCount;
   }

   @Column(name = "product_sold_count")
   public Integer getProductSoldCount()
   {
      return this.productSoldCount;
   }

   public void setProductSoldCount(Integer productSoldCount)
   {
      this.productSoldCount = productSoldCount;
   }

   @Column(name = "last_update_user_id", length = 45)
   public String getLastUpdateUserId()
   {
      return this.lastUpdateUserId;
   }

   public void setLastUpdateUserId(String lastUpdateUserId)
   {
      this.lastUpdateUserId = lastUpdateUserId;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "last_update_ts", length = 19)
   public Date getLastUpdateTs()
   {
      return this.lastUpdateTs;
   }

   public void setLastUpdateTs(Date lastUpdateTs)
   {
      this.lastUpdateTs = lastUpdateTs;
   }

}
