package org.agilekartV2.model;

// Generated Jul 16, 2015 1:41:40 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * ProductReview generated by hbm2java
 */
@Entity
@Table(name = "product_review"
      , catalog = "agilekartV2")
@XmlRootElement
public class ProductReview implements java.io.Serializable
{

   private String productReviewId;
   private String userId;
   private String productId;
   private Integer productRating;
   private String productReviewComment;
   private String lastUpdateUserId;
   private Date lastUpdateTs;

   public ProductReview()
   {
   }

   public ProductReview(String productReviewId, String userId, String productId)
   {
      this.productReviewId = productReviewId;
      this.userId = userId;
      this.productId = productId;
   }

   public ProductReview(String productReviewId, String userId, String productId, Integer productRating, String productReviewComment, String lastUpdateUserId, Date lastUpdateTs)
   {
      this.productReviewId = productReviewId;
      this.userId = userId;
      this.productId = productId;
      this.productRating = productRating;
      this.productReviewComment = productReviewComment;
      this.lastUpdateUserId = lastUpdateUserId;
      this.lastUpdateTs = lastUpdateTs;
   }

   @Id
   @Column(name = "product_review_id", unique = true, nullable = false, length = 45)
   public String getProductReviewId()
   {
      return this.productReviewId;
   }

   public void setProductReviewId(String productReviewId)
   {
      this.productReviewId = productReviewId;
   }

   @Column(name = "user_id", nullable = false, length = 45)
   public String getUserId()
   {
      return this.userId;
   }

   public void setUserId(String userId)
   {
      this.userId = userId;
   }

   @Column(name = "product_id", nullable = false, length = 45)
   public String getProductId()
   {
      return this.productId;
   }

   public void setProductId(String productId)
   {
      this.productId = productId;
   }

   @Column(name = "product_rating")
   public Integer getProductRating()
   {
      return this.productRating;
   }

   public void setProductRating(Integer productRating)
   {
      this.productRating = productRating;
   }

   @Column(name = "product_review_comment", length = 500)
   public String getProductReviewComment()
   {
      return this.productReviewComment;
   }

   public void setProductReviewComment(String productReviewComment)
   {
      this.productReviewComment = productReviewComment;
   }

   @Column(name = "last_update_user_id", length = 45)
   public String getLastUpdateUserId()
   {
      return this.lastUpdateUserId;
   }

   public void setLastUpdateUserId(String lastUpdateUserId)
   {
      this.lastUpdateUserId = lastUpdateUserId;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "last_update_ts", length = 19)
   public Date getLastUpdateTs()
   {
      return this.lastUpdateTs;
   }

   public void setLastUpdateTs(Date lastUpdateTs)
   {
      this.lastUpdateTs = lastUpdateTs;
   }

}
