package org.agilekartV2.model;

// Generated Jul 16, 2015 1:41:40 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Tax generated by hbm2java
 */
@Entity
@Table(name = "tax"
      , catalog = "agilekartV2")
@XmlRootElement
public class Tax implements java.io.Serializable
{

   private String taxId;
   private Float taxRate;
   private Byte taxIsActive;
   private String lastUpdateUserId;
   private Date lastUpdateTs;

   public Tax()
   {
   }

   public Tax(String taxId)
   {
      this.taxId = taxId;
   }

   public Tax(String taxId, Float taxRate, Byte taxIsActive, String lastUpdateUserId, Date lastUpdateTs)
   {
      this.taxId = taxId;
      this.taxRate = taxRate;
      this.taxIsActive = taxIsActive;
      this.lastUpdateUserId = lastUpdateUserId;
      this.lastUpdateTs = lastUpdateTs;
   }

   @Id
   @Column(name = "tax_id", unique = true, nullable = false, length = 45)
   public String getTaxId()
   {
      return this.taxId;
   }

   public void setTaxId(String taxId)
   {
      this.taxId = taxId;
   }

   @Column(name = "tax_rate", precision = 12, scale = 0)
   public Float getTaxRate()
   {
      return this.taxRate;
   }

   public void setTaxRate(Float taxRate)
   {
      this.taxRate = taxRate;
   }

   @Column(name = "tax_is_active")
   public Byte getTaxIsActive()
   {
      return this.taxIsActive;
   }

   public void setTaxIsActive(Byte taxIsActive)
   {
      this.taxIsActive = taxIsActive;
   }

   @Column(name = "last_update_user_id", length = 45)
   public String getLastUpdateUserId()
   {
      return this.lastUpdateUserId;
   }

   public void setLastUpdateUserId(String lastUpdateUserId)
   {
      this.lastUpdateUserId = lastUpdateUserId;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "last_update_ts", length = 19)
   public Date getLastUpdateTs()
   {
      return this.lastUpdateTs;
   }

   public void setLastUpdateTs(Date lastUpdateTs)
   {
      this.lastUpdateTs = lastUpdateTs;
   }

}
