package org.agilekartV2.model;

// Generated Jul 16, 2015 1:41:40 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * TaxRuleMerchant generated by hbm2java
 */
@Entity
@Table(name = "tax_rule_merchant"
      , catalog = "agilekartV2")
@XmlRootElement
public class TaxRuleMerchant implements java.io.Serializable
{

   private String taxRuleMerchantId;
   private String taxRuleId;
   private String merchantId;
   private String lastUpdateUserId;
   private Date lastUpdateTs;

   public TaxRuleMerchant()
   {
   }

   public TaxRuleMerchant(String taxRuleMerchantId, String taxRuleId, String merchantId)
   {
      this.taxRuleMerchantId = taxRuleMerchantId;
      this.taxRuleId = taxRuleId;
      this.merchantId = merchantId;
   }

   public TaxRuleMerchant(String taxRuleMerchantId, String taxRuleId, String merchantId, String lastUpdateUserId, Date lastUpdateTs)
   {
      this.taxRuleMerchantId = taxRuleMerchantId;
      this.taxRuleId = taxRuleId;
      this.merchantId = merchantId;
      this.lastUpdateUserId = lastUpdateUserId;
      this.lastUpdateTs = lastUpdateTs;
   }

   @Id
   @Column(name = "tax_rule_merchant_id", unique = true, nullable = false, length = 45)
   public String getTaxRuleMerchantId()
   {
      return this.taxRuleMerchantId;
   }

   public void setTaxRuleMerchantId(String taxRuleMerchantId)
   {
      this.taxRuleMerchantId = taxRuleMerchantId;
   }

   @Column(name = "tax_rule_id", nullable = false, length = 45)
   public String getTaxRuleId()
   {
      return this.taxRuleId;
   }

   public void setTaxRuleId(String taxRuleId)
   {
      this.taxRuleId = taxRuleId;
   }

   @Column(name = "merchant_id", nullable = false, length = 45)
   public String getMerchantId()
   {
      return this.merchantId;
   }

   public void setMerchantId(String merchantId)
   {
      this.merchantId = merchantId;
   }

   @Column(name = "last_update_user_id", length = 45)
   public String getLastUpdateUserId()
   {
      return this.lastUpdateUserId;
   }

   public void setLastUpdateUserId(String lastUpdateUserId)
   {
      this.lastUpdateUserId = lastUpdateUserId;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "last_update_ts", length = 19)
   public Date getLastUpdateTs()
   {
      return this.lastUpdateTs;
   }

   public void setLastUpdateTs(Date lastUpdateTs)
   {
      this.lastUpdateTs = lastUpdateTs;
   }

}
