package org.agilekartV2.model;

// Generated Jul 16, 2015 1:41:40 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * TaxRule generated by hbm2java
 */
@Entity
@Table(name = "tax_rule"
      , catalog = "agilekartV2")
@XmlRootElement
public class TaxRule implements java.io.Serializable
{

   private String taxRuleId;
   private String taxId;
   private String taxRuleName;
   private String stateCd;
   private String countryCd;
   private String lastUpdateUserId;
   private Date lastUpdateTs;

   public TaxRule()
   {
   }

   public TaxRule(String taxRuleId, String taxId)
   {
      this.taxRuleId = taxRuleId;
      this.taxId = taxId;
   }

   public TaxRule(String taxRuleId, String taxId, String taxRuleName, String stateCd, String countryCd, String lastUpdateUserId, Date lastUpdateTs)
   {
      this.taxRuleId = taxRuleId;
      this.taxId = taxId;
      this.taxRuleName = taxRuleName;
      this.stateCd = stateCd;
      this.countryCd = countryCd;
      this.lastUpdateUserId = lastUpdateUserId;
      this.lastUpdateTs = lastUpdateTs;
   }

   @Id
   @Column(name = "tax_rule_id", unique = true, nullable = false, length = 45)
   public String getTaxRuleId()
   {
      return this.taxRuleId;
   }

   public void setTaxRuleId(String taxRuleId)
   {
      this.taxRuleId = taxRuleId;
   }

   @Column(name = "tax_id", nullable = false, length = 45)
   public String getTaxId()
   {
      return this.taxId;
   }

   public void setTaxId(String taxId)
   {
      this.taxId = taxId;
   }

   @Column(name = "tax_rule_name", length = 45)
   public String getTaxRuleName()
   {
      return this.taxRuleName;
   }

   public void setTaxRuleName(String taxRuleName)
   {
      this.taxRuleName = taxRuleName;
   }

   @Column(name = "state_cd", length = 45)
   public String getStateCd()
   {
      return this.stateCd;
   }

   public void setStateCd(String stateCd)
   {
      this.stateCd = stateCd;
   }

   @Column(name = "country_cd", length = 45)
   public String getCountryCd()
   {
      return this.countryCd;
   }

   public void setCountryCd(String countryCd)
   {
      this.countryCd = countryCd;
   }

   @Column(name = "last_update_user_id", length = 45)
   public String getLastUpdateUserId()
   {
      return this.lastUpdateUserId;
   }

   public void setLastUpdateUserId(String lastUpdateUserId)
   {
      this.lastUpdateUserId = lastUpdateUserId;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "last_update_ts", length = 19)
   public Date getLastUpdateTs()
   {
      return this.lastUpdateTs;
   }

   public void setLastUpdateTs(Date lastUpdateTs)
   {
      this.lastUpdateTs = lastUpdateTs;
   }

}
