package org.agilekartV2.model;

// Generated Jul 16, 2015 1:41:40 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * UserAddress generated by hbm2java
 */
@Entity
@Table(name = "user_address"
      , catalog = "agilekartV2")
@XmlRootElement
public class UserAddress implements java.io.Serializable
{

   private String addressId;
   private String userAddress;
   private String userAddress2;
   private String userCity;
   private String userCountry;
   private String userFax;
   private String userFirstName;
   private String userLastName;
   private String userPhone;
   private String userState;
   private String userTypeName;
   private String userZip;
   private String userId;
   private String lastUpdateUserId;
   private Date lastUpdateTs;

   public UserAddress()
   {
   }

   public UserAddress(String addressId, String userId)
   {
      this.addressId = addressId;
      this.userId = userId;
   }

   public UserAddress(String addressId, String userAddress, String userAddress2, String userCity, String userCountry, String userFax, String userFirstName, String userLastName, String userPhone, String userState, String userTypeName, String userZip, String userId, String lastUpdateUserId, Date lastUpdateTs)
   {
      this.addressId = addressId;
      this.userAddress = userAddress;
      this.userAddress2 = userAddress2;
      this.userCity = userCity;
      this.userCountry = userCountry;
      this.userFax = userFax;
      this.userFirstName = userFirstName;
      this.userLastName = userLastName;
      this.userPhone = userPhone;
      this.userState = userState;
      this.userTypeName = userTypeName;
      this.userZip = userZip;
      this.userId = userId;
      this.lastUpdateUserId = lastUpdateUserId;
      this.lastUpdateTs = lastUpdateTs;
   }

   @Id
   @Column(name = "address_id", unique = true, nullable = false, length = 45)
   public String getAddressId()
   {
      return this.addressId;
   }

   public void setAddressId(String addressId)
   {
      this.addressId = addressId;
   }

   @Column(name = "user_address", length = 100)
   public String getUserAddress()
   {
      return this.userAddress;
   }

   public void setUserAddress(String userAddress)
   {
      this.userAddress = userAddress;
   }

   @Column(name = "user_address2", length = 50)
   public String getUserAddress2()
   {
      return this.userAddress2;
   }

   public void setUserAddress2(String userAddress2)
   {
      this.userAddress2 = userAddress2;
   }

   @Column(name = "user_city", length = 90)
   public String getUserCity()
   {
      return this.userCity;
   }

   public void setUserCity(String userCity)
   {
      this.userCity = userCity;
   }

   @Column(name = "user_country", length = 20)
   public String getUserCountry()
   {
      return this.userCountry;
   }

   public void setUserCountry(String userCountry)
   {
      this.userCountry = userCountry;
   }

   @Column(name = "user_fax", length = 20)
   public String getUserFax()
   {
      return this.userFax;
   }

   public void setUserFax(String userFax)
   {
      this.userFax = userFax;
   }

   @Column(name = "user_first_name", length = 50)
   public String getUserFirstName()
   {
      return this.userFirstName;
   }

   public void setUserFirstName(String userFirstName)
   {
      this.userFirstName = userFirstName;
   }

   @Column(name = "user_last_name", length = 50)
   public String getUserLastName()
   {
      return this.userLastName;
   }

   public void setUserLastName(String userLastName)
   {
      this.userLastName = userLastName;
   }

   @Column(name = "user_phone", length = 20)
   public String getUserPhone()
   {
      return this.userPhone;
   }

   public void setUserPhone(String userPhone)
   {
      this.userPhone = userPhone;
   }

   @Column(name = "user_state", length = 20)
   public String getUserState()
   {
      return this.userState;
   }

   public void setUserState(String userState)
   {
      this.userState = userState;
   }

   @Column(name = "user_type_name", length = 50)
   public String getUserTypeName()
   {
      return this.userTypeName;
   }

   public void setUserTypeName(String userTypeName)
   {
      this.userTypeName = userTypeName;
   }

   @Column(name = "user_zip", length = 12)
   public String getUserZip()
   {
      return this.userZip;
   }

   public void setUserZip(String userZip)
   {
      this.userZip = userZip;
   }

   @Column(name = "user_id", nullable = false, length = 45)
   public String getUserId()
   {
      return this.userId;
   }

   public void setUserId(String userId)
   {
      this.userId = userId;
   }

   @Column(name = "last_update_user_id", length = 45)
   public String getLastUpdateUserId()
   {
      return this.lastUpdateUserId;
   }

   public void setLastUpdateUserId(String lastUpdateUserId)
   {
      this.lastUpdateUserId = lastUpdateUserId;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "last_update_ts", length = 19)
   public Date getLastUpdateTs()
   {
      return this.lastUpdateTs;
   }

   public void setLastUpdateTs(Date lastUpdateTs)
   {
      this.lastUpdateTs = lastUpdateTs;
   }

}
