package org.agilekartV2.model;

// Generated Jul 16, 2015 1:41:40 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * UserRewards generated by hbm2java
 */
@Entity
@Table(name = "user_rewards"
      , catalog = "agilekartV2")
@XmlRootElement
public class UserRewards implements java.io.Serializable
{

   private String rewardId;
   private String userId;
   private String orderId;
   private Integer pointsEarned;
   private Integer pointsRedeemed;
   private Date expiryDate;
   private Date pointsEarnedDate;
   private Date pointsRedeeemedDate;
   private String tierId;
   private Integer totalPointsEarned;
   private Integer totalPointsRedeemed;
   private String lastUpdateUserId;
   private Date lastUpdateTs;

   public UserRewards()
   {
   }

   public UserRewards(String rewardId, String userId, String orderId, String tierId)
   {
      this.rewardId = rewardId;
      this.userId = userId;
      this.orderId = orderId;
      this.tierId = tierId;
   }

   public UserRewards(String rewardId, String userId, String orderId, Integer pointsEarned, Integer pointsRedeemed, Date expiryDate, Date pointsEarnedDate, Date pointsRedeeemedDate, String tierId, Integer totalPointsEarned, Integer totalPointsRedeemed, String lastUpdateUserId, Date lastUpdateTs)
   {
      this.rewardId = rewardId;
      this.userId = userId;
      this.orderId = orderId;
      this.pointsEarned = pointsEarned;
      this.pointsRedeemed = pointsRedeemed;
      this.expiryDate = expiryDate;
      this.pointsEarnedDate = pointsEarnedDate;
      this.pointsRedeeemedDate = pointsRedeeemedDate;
      this.tierId = tierId;
      this.totalPointsEarned = totalPointsEarned;
      this.totalPointsRedeemed = totalPointsRedeemed;
      this.lastUpdateUserId = lastUpdateUserId;
      this.lastUpdateTs = lastUpdateTs;
   }

   @Id
   @Column(name = "reward_id", unique = true, nullable = false, length = 45)
   public String getRewardId()
   {
      return this.rewardId;
   }

   public void setRewardId(String rewardId)
   {
      this.rewardId = rewardId;
   }

   @Column(name = "user_id", nullable = false, length = 45)
   public String getUserId()
   {
      return this.userId;
   }

   public void setUserId(String userId)
   {
      this.userId = userId;
   }

   @Column(name = "order_id", nullable = false, length = 45)
   public String getOrderId()
   {
      return this.orderId;
   }

   public void setOrderId(String orderId)
   {
      this.orderId = orderId;
   }

   @Column(name = "points_earned")
   public Integer getPointsEarned()
   {
      return this.pointsEarned;
   }

   public void setPointsEarned(Integer pointsEarned)
   {
      this.pointsEarned = pointsEarned;
   }

   @Column(name = "points_redeemed")
   public Integer getPointsRedeemed()
   {
      return this.pointsRedeemed;
   }

   public void setPointsRedeemed(Integer pointsRedeemed)
   {
      this.pointsRedeemed = pointsRedeemed;
   }

   @Temporal(TemporalType.DATE)
   @Column(name = "expiry_date", length = 10)
   public Date getExpiryDate()
   {
      return this.expiryDate;
   }

   public void setExpiryDate(Date expiryDate)
   {
      this.expiryDate = expiryDate;
   }

   @Temporal(TemporalType.DATE)
   @Column(name = "points_earned_date", length = 10)
   public Date getPointsEarnedDate()
   {
      return this.pointsEarnedDate;
   }

   public void setPointsEarnedDate(Date pointsEarnedDate)
   {
      this.pointsEarnedDate = pointsEarnedDate;
   }

   @Temporal(TemporalType.DATE)
   @Column(name = "points_redeeemed_date", length = 10)
   public Date getPointsRedeeemedDate()
   {
      return this.pointsRedeeemedDate;
   }

   public void setPointsRedeeemedDate(Date pointsRedeeemedDate)
   {
      this.pointsRedeeemedDate = pointsRedeeemedDate;
   }

   @Column(name = "tier_id", nullable = false, length = 45)
   public String getTierId()
   {
      return this.tierId;
   }

   public void setTierId(String tierId)
   {
      this.tierId = tierId;
   }

   @Column(name = "total_points_earned")
   public Integer getTotalPointsEarned()
   {
      return this.totalPointsEarned;
   }

   public void setTotalPointsEarned(Integer totalPointsEarned)
   {
      this.totalPointsEarned = totalPointsEarned;
   }

   @Column(name = "total_points_redeemed")
   public Integer getTotalPointsRedeemed()
   {
      return this.totalPointsRedeemed;
   }

   public void setTotalPointsRedeemed(Integer totalPointsRedeemed)
   {
      this.totalPointsRedeemed = totalPointsRedeemed;
   }

   @Column(name = "last_update_user_id", length = 45)
   public String getLastUpdateUserId()
   {
      return this.lastUpdateUserId;
   }

   public void setLastUpdateUserId(String lastUpdateUserId)
   {
      this.lastUpdateUserId = lastUpdateUserId;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "last_update_ts", length = 19)
   public Date getLastUpdateTs()
   {
      return this.lastUpdateTs;
   }

   public void setLastUpdateTs(Date lastUpdateTs)
   {
      this.lastUpdateTs = lastUpdateTs;
   }

}
