package org.agilekartV2.model;

// Generated Jul 16, 2015 1:41:40 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * UserFavourites generated by hbm2java
 */
@Entity
@Table(name = "user_favourites"
      , catalog = "agilekartV2")
@XmlRootElement
public class UserFavourites implements java.io.Serializable
{

   private String userFavouriteId;
   private String userId;
   private String favouriteId;
   private String merchantId;
   private String orderFl;
   private String lastUpdateUserId;
   private Date lastUpdateTs;

   public UserFavourites()
   {
   }

   public UserFavourites(String userFavouriteId, String userId, String favouriteId)
   {
      this.userFavouriteId = userFavouriteId;
      this.userId = userId;
      this.favouriteId = favouriteId;
   }

   public UserFavourites(String userFavouriteId, String userId, String favouriteId, String merchantId, String orderFl, String lastUpdateUserId, Date lastUpdateTs)
   {
      this.userFavouriteId = userFavouriteId;
      this.userId = userId;
      this.favouriteId = favouriteId;
      this.merchantId = merchantId;
      this.orderFl = orderFl;
      this.lastUpdateUserId = lastUpdateUserId;
      this.lastUpdateTs = lastUpdateTs;
   }

   @Id
   @Column(name = "user_favourite_id", unique = true, nullable = false, length = 45)
   public String getUserFavouriteId()
   {
      return this.userFavouriteId;
   }

   public void setUserFavouriteId(String userFavouriteId)
   {
      this.userFavouriteId = userFavouriteId;
   }

   @Column(name = "user_id", nullable = false, length = 45)
   public String getUserId()
   {
      return this.userId;
   }

   public void setUserId(String userId)
   {
      this.userId = userId;
   }

   @Column(name = "favourite_id", nullable = false, length = 45)
   public String getFavouriteId()
   {
      return this.favouriteId;
   }

   public void setFavouriteId(String favouriteId)
   {
      this.favouriteId = favouriteId;
   }

   @Column(name = "merchant_id", length = 45)
   public String getMerchantId()
   {
      return this.merchantId;
   }

   public void setMerchantId(String merchantId)
   {
      this.merchantId = merchantId;
   }

   @Column(name = "order_fl", length = 45)
   public String getOrderFl()
   {
      return this.orderFl;
   }

   public void setOrderFl(String orderFl)
   {
      this.orderFl = orderFl;
   }

   @Column(name = "last_update_user_id", length = 45)
   public String getLastUpdateUserId()
   {
      return this.lastUpdateUserId;
   }

   public void setLastUpdateUserId(String lastUpdateUserId)
   {
      this.lastUpdateUserId = lastUpdateUserId;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "last_update_ts", length = 19)
   public Date getLastUpdateTs()
   {
      return this.lastUpdateTs;
   }

   public void setLastUpdateTs(Date lastUpdateTs)
   {
      this.lastUpdateTs = lastUpdateTs;
   }

}
