package org.agilekartV2.model;

// Generated Jul 16, 2015 1:41:40 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users"
      , catalog = "agilekartV2")
@XmlRootElement
public class Users implements java.io.Serializable
{

   private String userId;
   private String userEmail;
   private String userPassword;
   private String userFirstName;
   private String userLastName;
   private Boolean userEmailVerified;
   private Date userRegistrationDate;
   private String userVerificationCode;
   private Integer userRewardPoints;
   private String userPhoneNo;
   private String lastUpdateUserId;
   private Date lastUpdateTs;

   public Users()
   {
   }

   public Users(String userId)
   {
      this.userId = userId;
   }

   public Users(String userId, String userEmail, String userPassword, String userFirstName, String userLastName, Boolean userEmailVerified, Date userRegistrationDate, String userVerificationCode, Integer userRewardPoints, String userPhoneNo, String lastUpdateUserId, Date lastUpdateTs)
   {
      this.userId = userId;
      this.userEmail = userEmail;
      this.userPassword = userPassword;
      this.userFirstName = userFirstName;
      this.userLastName = userLastName;
      this.userEmailVerified = userEmailVerified;
      this.userRegistrationDate = userRegistrationDate;
      this.userVerificationCode = userVerificationCode;
      this.userRewardPoints = userRewardPoints;
      this.userPhoneNo = userPhoneNo;
      this.lastUpdateUserId = lastUpdateUserId;
      this.lastUpdateTs = lastUpdateTs;
   }

   @Id
   @Column(name = "user_id", unique = true, nullable = false, length = 45)
   public String getUserId()
   {
      return this.userId;
   }

   public void setUserId(String userId)
   {
      this.userId = userId;
   }

   @Column(name = "user_email", length = 500)
   public String getUserEmail()
   {
      return this.userEmail;
   }

   public void setUserEmail(String userEmail)
   {
      this.userEmail = userEmail;
   }

   @Column(name = "user_password", length = 500)
   public String getUserPassword()
   {
      return this.userPassword;
   }

   public void setUserPassword(String userPassword)
   {
      this.userPassword = userPassword;
   }

   @Column(name = "user_first_name", length = 50)
   public String getUserFirstName()
   {
      return this.userFirstName;
   }

   public void setUserFirstName(String userFirstName)
   {
      this.userFirstName = userFirstName;
   }

   @Column(name = "user_last_name", length = 50)
   public String getUserLastName()
   {
      return this.userLastName;
   }

   public void setUserLastName(String userLastName)
   {
      this.userLastName = userLastName;
   }

   @Column(name = "user_email_verified")
   public Boolean getUserEmailVerified()
   {
      return this.userEmailVerified;
   }

   public void setUserEmailVerified(Boolean userEmailVerified)
   {
      this.userEmailVerified = userEmailVerified;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "user_registration_date", length = 19)
   public Date getUserRegistrationDate()
   {
      return this.userRegistrationDate;
   }

   public void setUserRegistrationDate(Date userRegistrationDate)
   {
      this.userRegistrationDate = userRegistrationDate;
   }

   @Column(name = "user_verification_code", length = 20)
   public String getUserVerificationCode()
   {
      return this.userVerificationCode;
   }

   public void setUserVerificationCode(String userVerificationCode)
   {
      this.userVerificationCode = userVerificationCode;
   }

   @Column(name = "user_reward_points")
   public Integer getUserRewardPoints()
   {
      return this.userRewardPoints;
   }

   public void setUserRewardPoints(Integer userRewardPoints)
   {
      this.userRewardPoints = userRewardPoints;
   }

   @Column(name = "user_phone_no", length = 20)
   public String getUserPhoneNo()
   {
      return this.userPhoneNo;
   }

   public void setUserPhoneNo(String userPhoneNo)
   {
      this.userPhoneNo = userPhoneNo;
   }

   @Column(name = "last_update_user_id", length = 45)
   public String getLastUpdateUserId()
   {
      return this.lastUpdateUserId;
   }

   public void setLastUpdateUserId(String lastUpdateUserId)
   {
      this.lastUpdateUserId = lastUpdateUserId;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "last_update_ts", length = 19)
   public Date getLastUpdateTs()
   {
      return this.lastUpdateTs;
   }

   public void setLastUpdateTs(Date lastUpdateTs)
   {
      this.lastUpdateTs = lastUpdateTs;
   }

}
